import {
  Beaker, Microscope, Dna, HeartPulse, TestTube,
  FlaskConical, Cpu, ShieldCheck, Activity, Layers,
} from "lucide-react";

export type Brand = { id: string; name: string; short: string; blurb: string; accent: string; };
export type Category = { id: string; name: string; icon: React.ReactNode; };

export type PackagingVariant = {
  name: string;
  catalogueNumber: string;
  units: string;
  format?: string;
};

export type Product = {
  id: string; name: string; brand: string; category: string;
  subcategory?: string; description: string; featured?: boolean; tags?: string[];
  image?: string;
  highlights?: string[]; features?: string[]; applications?: string[];
  specs?: Record<string, string>; catalogueNumber?: string;
  packaging?: PackagingVariant[];
  relatedProducts?: string[];
};

export const brands: Brand[] = [
  { id: "onelambda", name: "One Lambda (Thermo Fisher Scientific)", short: "One Lambda", blurb: "Global leader in transplant diagnostics — HLA typing, antibody detection, and crossmatch solutions trusted worldwide.", accent: "#D71920" },
  { id: "merck", name: "Merck Sigma-Aldrich", short: "Merck", blurb: "Reagents, antibodies and research chemicals — life-science gold standard.", accent: "#003366" },
  { id: "luminex", name: "Luminex Corp", short: "Luminex", blurb: "xMAP® multiplex assay technology for high-throughput labs.", accent: "#2EA3F2" },
  { id: "diasorin", name: "DiaSorin", short: "DiaSorin", blurb: "Immunoassays and molecular diagnostics powered by LIAISON® systems.", accent: "#0F4C81" },
  { id: "cytek", name: "CytekBio", short: "Cytek", blurb: "Full-spectrum flow cytometry redefining cellular analysis.", accent: "#5E2A84" },
  { id: "ngene", name: "NgeneBio", short: "NgeneBio", blurb: "NGS-based precision oncology diagnostics.", accent: "#00A19A" },
  { id: "hkm", name: "HKM Bio", short: "HKM", blurb: "Reliable laboratory equipment — centrifuges, incubators, and safety cabinets.", accent: "#7A8B99" },
  { id: "biolegend", name: "BioLegend", short: "BioLegend", blurb: "World-class antibodies and reagents for flow cytometry and ELISA.", accent: "#E94B3C" },
];

export const categories: Category[] = [
  { id: "multiplex", name: "Multiplex Analyzers", icon: <Cpu className="h-4 w-4" /> },
  { id: "flow", name: "Flow Cytometers", icon: <Microscope className="h-4 w-4" /> },
  { id: "transplant", name: "Transplant Diagnostics", icon: <HeartPulse className="h-4 w-4" /> },
  { id: "molecular", name: "Molecular Diagnostics", icon: <Dna className="h-4 w-4" /> },
  { id: "immuno", name: "Immunoassays", icon: <ShieldCheck className="h-4 w-4" /> },
  { id: "ngs", name: "NGS / Sequencing", icon: <FlaskConical className="h-4 w-4" /> },
  { id: "antibodies", name: "Antibodies & Reagents", icon: <TestTube className="h-4 w-4" /> },
  { id: "equipment", name: "Lab Equipment & Consumables", icon: <Beaker className="h-4 w-4" /> },
  { id: "serological", name: "Serological Typing", icon: <Activity className="h-4 w-4" /> },
  { id: "posttransplant", name: "Post-Transplant Monitoring", icon: <Layers className="h-4 w-4" /> },
];

// Navigation tree mirroring vhbio.com One Lambda structure exactly
export const oneLambdaNav: Record<string, Record<string, string[]>> = {
  "Antibody Detection": {
    "Luminex-based HLA Antibody Identification": ["ol-labscreen-sa1","ol-labscreen-sa2","ol-labscreen-mixed","ol-labscreen-pra","ol-labscreen-multi","ol-labscreen-mica","ol-labscreen-explex","ol-labscreen-supplement","ol-labscreen-ancillary"],
    "Complement Binding HLA Antibody Identification": ["ol-c1qscreen"],
    "Flow Cytometry Based HLA Antibody Identification": ["ol-flowpra-sa","ol-flowpra-specific","ol-flowpra-ancillary"],
    "Advanced Crossmatch Testing": ["ol-flowdsa-xm"],
    "Advanced Antibody Testing": ["ol-magsort"],
    "ELISA-Based HLA Antibody Identification": ["ol-lat","ol-lat-mixed","ol-lat-class1"],
    "ELISA-Based Non-HLA Antibody Identification": ["ol-at1r-etar"],
    "Non-HLA Luminex Based Antibody Identification": ["ol-labscreen-autoantibody"],
    "Serological-based HLA Antibody Identification": ["ol-lambda-cell-trays"],
  },
  "Molecular Typing": {
    "Next-Generation Sequencing": ["ol-alltype-ngs","ol-alltype-fastplex","ol-alltype-rapid","ol-hybritype"],
    "Sequence-Specific Primer Typing": ["ol-microssp-generic","ol-microssp-highres","ol-bulk-primers"],
    "Reverse SSO Typing": ["ol-labtype-sso","ol-labtype-ancillary"],
    "Sequence Based Typing": ["ol-secore-sbt","ol-secore-gssp"],
    "LinkSeq Real-Time PCR": ["ol-linkseq-hla-kir","ol-linkseq-hpa-abo","ol-linkseq-ancillary"],
    "Non-HLA Genotyping": ["ol-cytokine-genotyping","ol-hna-genotyping","ol-kir-sso"],
    "Molecular Biology Instrumentation": ["ol-qubit","ol-veritiPro"],
  },
  "Serological Typing": {
    "HLA Tissue Typing Trays": ["ol-terasaki-trays","ol-terasaki-supplement","ol-lmt"],
    "Serological Reagents": ["ol-b27-antibody","ol-cytotoxic-controls","ol-dynabeads","ol-fluoroquench","ol-bulk-monoclonal"],
  },
  "Instruments & Software": {
    "Readers & Analysers": ["ol-labscan3d","ol-labscan100"],
    "Software": ["ol-typestream","ol-fusion"],
    "Automated Pipettor": ["ol-hla-pro"],
  },
  "Post-Transplant Monitoring": {
    "Chimerism Monitoring": ["ol-chimerism-ngs","ol-chimerism"],
    "Donor-Derived Cell-Free DNA": ["ol-accept-cfdna"],
  },
};

export const products: Product[] = [
  // ═══ ONE LAMBDA — ANTIBODY DETECTION ═══════════════════════════════════════

  { id:"ol-labscreen-sa1", name:"LABScreen™ Single Antigen HLA Class I", brand:"onelambda", category:"transplant", subcategory:"Luminex-based HLA Antibody Identification",
    description:"High-resolution identification of HLA Class I antibodies (HLA-A, B, C) using Luminex xMAP® single-antigen bead technology. Each bead is coated with a single purified HLA antigen for precise antibody specificity determination.", featured:true,
    tags:["hla","transplant","antibody","class-i","luminex"],
    highlights:["Single-antigen resolution for HLA-A, B, C","Over 90 HLA Class I specificities covered","FDA 510(k) cleared, CE marked","Compatible with LABScan3D™ and FLEXMAP 3D®"],
    features:["Single purified recombinant HLA Class I antigen per bead","PE-conjugated anti-human IgG fluorescent detection","High inter-assay reproducibility","HLA Fusion™ software compatible","Interpretable with automated cut-off application"],
    applications:["Pre-transplant HLA antibody identification","Unacceptable antigen determination for transplant listing","Virtual crossmatch — Class I","Post-transplant donor-specific antibody (DSA) monitoring","Panel Reactive Antibody (PRA) assessment"],
    specs:{"HLA Loci":"HLA-A, B, C (Class I)","Specificities":"> 90","Detection Method":"PE anti-human IgG","Sample Type":"Human serum","Sample Volume":"20 µL per reaction","Incubation Time":"30 minutes","Regulatory Status":"FDA 510(k) cleared, CE marked"},
    packaging:[
      {name:"LABScreen™ Single Antigen Class I",catalogueNumber:"LS1A04",units:"1 Kit",format:"96-well microplate"},
      {name:"LABScreen™ Single Antigen Class I HD",catalogueNumber:"LS1A04HD",units:"1 Kit",format:"96-well microplate, High Definition"},
    ],
    relatedProducts:["ol-labscreen-sa2","ol-labscreen-mixed","ol-labscan3d","ol-c1qscreen"] },

  { id:"ol-labscreen-sa2", name:"LABScreen™ Single Antigen HLA Class II", brand:"onelambda", category:"transplant", subcategory:"Luminex-based HLA Antibody Identification",
    description:"Definitive identification of HLA Class II antibodies (DRB1, DRB3/4/5, DQA1, DQB1, DPA1, DPB1) using single-antigen bead technology on the Luminex xMAP® platform.", featured:true,
    tags:["hla","transplant","antibody","class-ii","luminex"],
    highlights:["Full DRB1, DRB3/4/5, DQA1, DQB1, DPA1, DPB1 coverage","Alpha-beta heterodimer pairs for DQ and DP loci","Detects rare and low-frequency specificities","FDA 510(k) cleared, CE marked"],
    features:["Single purified recombinant HLA Class II antigen per bead","Alpha-beta heterodimer pairs for DQ and DP","PE-conjugated anti-human IgG detection","HLA Fusion™ software compatible"],
    applications:["Pre-transplant HLA Class II antibody identification","DQ and DP antibody specificity determination","Virtual crossmatch — Class II","Post-transplant DSA monitoring"],
    specs:{"HLA Loci":"DRB1, DRB3/4/5, DQA1, DQB1, DPA1, DPB1","Specificities":"> 100","Detection Method":"PE anti-human IgG","Sample Volume":"20 µL per reaction","Regulatory Status":"FDA 510(k) cleared, CE marked"},
    packaging:[
      {name:"LABScreen™ Single Antigen Class II",catalogueNumber:"LS2A04",units:"1 Kit",format:"96-well microplate"},
      {name:"LABScreen™ Single Antigen Class II HD",catalogueNumber:"LS2A04HD",units:"1 Kit",format:"96-well microplate, High Definition"},
    ],
    relatedProducts:["ol-labscreen-sa1","ol-labscreen-mixed","ol-labscan3d","ol-c1qscreen"] },

  { id:"ol-labscreen-mixed", name:"LABScreen™ Mixed Class I & II Antibody Screening", brand:"onelambda", category:"transplant", subcategory:"Luminex-based HLA Antibody Identification",
    description:"Simultaneously screens for HLA Class I and Class II antibodies in a single well. Cost-effective first-line screening before single-antigen testing.",
    tags:["hla","transplant","screening"],
    packaging:[{name:"LABScreen™ Mixed",catalogueNumber:"LSMA04",units:"1 Kit",format:"96-well microplate"}],
    relatedProducts:["ol-labscreen-sa1","ol-labscreen-sa2"],
    features:["Simultaneous Class I and Class II antibody detection in one well","Mixed bead cocktail covering HLA-A, B, C, DR, DQ, DP antigens","PE-conjugated anti-human IgG fluorescent detection","Semi-quantitative MFI results","Compatible with LABScan3D™ and FLEXMAP 3D®"],
    applications:["Initial HLA antibody screening for all transplant candidates","Pre-transplant sensitisation assessment","Triage of samples for single-antigen testing","Post-transfusion sensitisation monitoring","Periodic re-screening of wait-listed patients"],
    specs:{"Coverage":"Class I (HLA-A,B,C) + Class II (DR,DQ,DP)","Assay Time":"~60 minutes","Sample Volume":"20 µL","Format":"96-well microplate","Regulatory":"FDA cleared, CE marked"},
   },

  { id:"ol-labscreen-pra", name:"LABScreen™ PRA", brand:"onelambda", category:"transplant", subcategory:"Luminex-based HLA Antibody Identification",
    description:"Panel Reactive Antibody (PRA) determination using Luminex xMAP® bead technology. Provides percentage PRA calculation for Class I and Class II.",
    tags:["hla","transplant","pra","screening"],
    packaging:[
      {name:"LABScreen™ PRA Class I",catalogueNumber:"LSPRA1A04",units:"1 Kit",format:"96-well microplate"},
      {name:"LABScreen™ PRA Class II",catalogueNumber:"LSPRA2A04",units:"1 Kit",format:"96-well microplate"},
    ],
    features:["Calculates percentage Panel Reactive Antibody (PRA)","Separate Class I and Class II PRA values","Luminex xMAP® bead-based assay","Automated PRA calculation with HLA Fusion™","Suitable for high-throughput screening"],
    applications:["Pre-transplant sensitisation level assessment","Wait-list PRA monitoring for organ allocation","Post-sensitisation event assessment (transfusion, pregnancy)","Determining need for single-antigen testing"],
    specs:{"PRA Output":"Class I % PRA, Class II % PRA","Format":"96-well microplate","Analyzer":"LABScan3D™, FLEXMAP 3D®","Sample Volume":"20 µL","Regulatory":"FDA cleared, CE marked"},
   },

  { id:"ol-labscreen-multi", name:"LABScreen™ Multi", brand:"onelambda", category:"transplant", subcategory:"Luminex-based HLA Antibody Identification",
    description:"Screens for HLA antibodies against a broad panel of common HLA specificities. Ideal for initial sensitization assessment.",
    tags:["hla","transplant","screening"],
    packaging:[{name:"LABScreen™ Multi",catalogueNumber:"LSMULIA4",units:"1 Kit",format:"96-well microplate"}],
    features:["Broad panel of representative HLA antigens per bead","Rapid initial sensitisation assessment","Semi-quantitative screening result","Compatible with LABScan3D™ and FLEXMAP 3D®"],
    applications:["Broad HLA antibody screen for newly listed transplant candidates","Screening to guide single-antigen test ordering","Cost-effective monitoring of wait-listed patients"],
    specs:{"Coverage":"Representative HLA-A,B,C,DR,DQ antigens","Format":"96-well microplate","Sample Volume":"20 µL","Regulatory":"FDA cleared, CE marked"},
   },

  { id:"ol-labscreen-mica", name:"LABScreen™ MICA Single Antigen Group 1", brand:"onelambda", category:"transplant", subcategory:"Luminex-based HLA Antibody Identification",
    description:"Detects and identifies antibodies against MICA antigens using Luminex bead technology — important for non-HLA antibody assessment in transplant.",
    tags:["mica","non-hla","transplant"],
    packaging:[{name:"LABScreen™ MICA Single Antigen Group 1",catalogueNumber:"LSM12A04",units:"1 Kit",format:"96-well microplate"}],
    features:["Single MICA antigen per bead for precise specificity identification","Detects IgG antibodies against MICA alleles","Luminex xMAP® platform","Compatible with LABScan3D™"],
    applications:["Non-HLA antibody identification for transplant risk assessment","MICA antibody monitoring post-transplant","Research into MICA antibody-mediated rejection"],
    specs:{"Target":"MICA antigens","Method":"Luminex single-antigen beads","Format":"96-well microplate","Regulatory":"CE marked, RUO in some regions"},
   },

  { id:"ol-labscreen-explex", name:"LABScreen™ Single Antigen ExPlex Assay", brand:"onelambda", category:"transplant", subcategory:"Luminex-based HLA Antibody Identification",
    description:"Extended single antigen panels with additional HLA specificities beyond standard SAB kits, improving resolution for complex patient profiles.",
    tags:["hla","transplant","antibody"],
    packaging:[
      {name:"LABScreen™ SA ExPlex Class I",catalogueNumber:"LSA1EPXA04",units:"1 Kit",format:"96-well microplate"},
      {name:"LABScreen™ SA ExPlex Class II",catalogueNumber:"LSA2EPXA04",units:"1 Kit",format:"96-well microplate"},
    ],
    features:["Extended antigen coverage beyond standard SAB panels","Identifies antibodies against additional rare HLA specificities","Luminex xMAP® bead platform","HLA Fusion™ software compatible"],
    applications:["Complex sensitised patients with broad antibody profiles","Identification of rare HLA antibody specificities","Confirmation of antibody patterns from standard SAB testing"],
    specs:{"Coverage":"Extended Class I and Class II specificities","Format":"96-well microplate","Analyzer":"LABScan3D™, FLEXMAP 3D®","Regulatory":"CE marked"},
   },

  { id:"ol-labscreen-supplement", name:"LABScreen™ Single Antigen Supplement", brand:"onelambda", category:"transplant", subcategory:"Luminex-based HLA Antibody Identification",
    description:"Supplementary single antigen beads providing additional HLA specificities to complement standard LABScreen™ SAB kits.",
    tags:["hla","transplant","supplement"],
    packaging:[{name:"LABScreen™ SA Supplement Class I",catalogueNumber:"LS1SUPPA04",units:"1 Kit",format:"96-well microplate"}],
    features:["Additional HLA-specific beads to supplement standard SAB","Covers specificities not in standard panels","Luminex xMAP® platform"],
    applications:["Supplementary testing for rare specificities","Completing antibody profiles in complex patients"],
    specs:{"Coverage":"Supplemental HLA Class I specificities","Format":"96-well microplate","Regulatory":"CE marked"},
   },

  { id:"ol-labscreen-ancillary", name:"LABScreen™ Ancillary Reagents", brand:"onelambda", category:"transplant", subcategory:"Luminex-based HLA Antibody Identification",
    description:"Supporting reagents for LABScreen™ assays: wash buffer, positive/negative controls, and serum diluent.",
    tags:["ancillary","reagents","labscreen"],
    packaging:[
      {name:"LABScreen™ Control Sera",catalogueNumber:"LSCONTXA",units:"1 Kit",format:"Control sera"},
      {name:"LABScreen™ Wash Buffer",catalogueNumber:"LSWASH0X",units:"1 Bottle",format:"Concentrate"},
    ],
    features:["Wash buffer optimised for LABScreen™ assays","Control sera for positive and negative QC","Serum diluent for sample normalisation","Pre-validated reagents for LABScreen™ workflows"],
    applications:["Quality control in LABScreen™ SAB and Mixed assays","Standardisation of laboratory workflows","Compliance with laboratory accreditation requirements"],
    specs:{"Components":"Wash buffer, control sera, diluent","Compatibility":"All LABScreen™ assay kits","Storage":"2–8 °C"},
   },

  { id:"ol-c1qscreen", name:"C1qScreen™ HLA Antibody Detection", brand:"onelambda", category:"transplant", subcategory:"Complement Binding HLA Antibody Identification",
    description:"Identifies complement-fixing HLA antibodies via C1q binding. Distinguishes clinically relevant complement-activating DSA — a key predictor of antibody-mediated rejection (AMR).", featured:true,
    tags:["complement","c1q","amr","transplant","dsa"],
    highlights:["Identifies complement-fixing (C1q-binding) HLA antibodies","Predicts risk of antibody-mediated rejection (AMR)","Single antigen bead format — Class I and Class II"],
    specs:{"Method":"C1q-binding Luminex bead assay","HLA Coverage":"Class I and Class II","Regulatory":"CE marked"},
    packaging:[
      {name:"C1qScreen™ Class I",catalogueNumber:"C1QSA1HD04",units:"1 Kit",format:"96-well microplate"},
      {name:"C1qScreen™ Class II",catalogueNumber:"C1QSA2HD04",units:"1 Kit",format:"96-well microplate"},
    ],
    relatedProducts:["ol-labscreen-sa1","ol-labscreen-sa2"],
    features:["Detects HLA antibodies that bind and fix complement component C1q","Single-antigen bead format for Class I and Class II","Distinguishes complement-fixing from non-complement-fixing DSA","High reproducibility with standardised C1q substrate"],
    applications:["Risk stratification of donor-specific antibodies (DSA)","Pre-transplant donor selection for sensitised patients","Post-transplant AMR diagnosis and monitoring","Clinical research on complement-activating HLA antibodies"],
   },

  { id:"ol-flowpra-sa", name:"FlowPRA™ Single Antigen", brand:"onelambda", category:"transplant", subcategory:"Flow Cytometry Based HLA Antibody Identification",
    description:"Identifies HLA Class I and Class II antibodies by flow cytometry using beads coated with individual HLA antigens. Designed for high-PRA patients.",
    tags:["hla","flow-cytometry","pra","transplant"],
    packaging:[
      {name:"FlowPRA™ Single Antigen Class I",catalogueNumber:"03FL1HD",units:"1 Kit",format:"Flow cytometry"},
      {name:"FlowPRA™ Single Antigen Class II",catalogueNumber:"03FL2HD",units:"1 Kit",format:"Flow cytometry"},
    ],
    features:["Individual HLA antigens on microbeads for single-antigen resolution","Flow cytometer compatible — no dedicated analyser needed","Class I and Class II separate kits","PE fluorescent detection"],
    applications:["HLA antibody identification by flow cytometry","Pre- and post-transplant antibody monitoring","Confirmation of Luminex-based antibody results"],
    specs:{"Method":"Flow cytometry bead-based assay","HLA Coverage":"Class I and Class II (separate kits)","Detection":"PE fluorescence","Equipment":"Standard flow cytometer","Regulatory":"CE marked"},
   },

  { id:"ol-flowpra-specific", name:"FlowPRA™ Specific", brand:"onelambda", category:"transplant", subcategory:"Flow Cytometry Based HLA Antibody Identification",
    description:"Flow cytometry-based screening using microbeads coated with pooled HLA antigens for rapid antibody screening.",
    tags:["hla","flow-cytometry","screening"],
    packaging:[
      {name:"FlowPRA™ Specific Class I",catalogueNumber:"03FLC1S",units:"1 Kit",format:"Flow cytometry"},
      {name:"FlowPRA™ Specific Class II",catalogueNumber:"03FLC2S",units:"1 Kit",format:"Flow cytometry"},
    ],
    features:["Pooled HLA antigen microbeads for rapid screening","Flow cytometry readout","Separate Class I and Class II screening kits","Semi-quantitative result"],
    applications:["Initial HLA antibody screening by flow cytometry","PRA estimation for clinical decision-making","Screening before single-antigen identification"],
    specs:{"Method":"Flow cytometry pooled bead screening","Format":"Class I and Class II kits","Equipment":"Standard flow cytometer","Regulatory":"CE marked"},
   },

  { id:"ol-flowpra-ancillary", name:"FlowPRA™ Ancillary Products", brand:"onelambda", category:"transplant", subcategory:"Flow Cytometry Based HLA Antibody Identification",
    description:"Supporting reagents for FlowPRA™ assays: control beads, wash buffer, and reagent packs.",
    tags:["ancillary","flow-cytometry"],
    packaging:[{name:"FlowPRA™ Control Beads",catalogueNumber:"03FLCB",units:"1 Vial",format:"Control beads"}],
    features:["Pre-validated control beads for assay QC","Wash buffer optimised for FlowPRA™ protocols","Supports laboratory accreditation requirements"],
    applications:["Quality control for FlowPRA™ assays","Workflow standardisation in flow cytometry HLA labs"],
    specs:{"Components":"Control beads, wash buffer","Compatibility":"All FlowPRA™ assay kits"},
   },

  { id:"ol-flowdsa-xm", name:"FlowDSA-XM™ Advanced Crossmatch", brand:"onelambda", category:"transplant", subcategory:"Advanced Crossmatch Testing",
    description:"Advanced flow cytometry crossmatch for specific detection of donor-directed HLA antibodies. Greater sensitivity than standard CDC crossmatch.",
    tags:["crossmatch","dsa","flow-cytometry","transplant"],
    packaging:[{name:"FlowDSA-XM™",catalogueNumber:"FLOWDSA",units:"1 Kit",format:"Flow cytometry"}],
    features:["Detects donor-specific HLA antibodies by flow cytometry","Greater sensitivity than CDC crossmatch","Class I and Class II DSA identification","Compatible with standard flow cytometers"],
    applications:["Virtual and physical crossmatch for transplant donors","Detection of low-level DSA missed by CDC","Pre-transplant DSA risk assessment","Post-transplant monitoring for de novo DSA"],
    specs:{"Method":"Flow cytometry crossmatch","Sensitivity":"Superior to CDC crossmatch","HLA Coverage":"Class I and Class II","Equipment":"Standard flow cytometer","Regulatory":"CE marked"},
   },

  { id:"ol-magsort", name:"One Lambda™ MagSort™", brand:"onelambda", category:"transplant", subcategory:"Advanced Antibody Testing",
    description:"Magnetic bead-based technology for advanced HLA antibody testing and prozone/hook effect removal. Improves antibody detection accuracy.",
    tags:["antibody","magsort","prozone"],
    packaging:[{name:"MagSort™ Class I & II",catalogueNumber:"MAGSORT04",units:"1 Kit",format:"Magnetic beads"}],
    features:["Magnetic bead separation of interfering factors","Removes prozone/hook-effect causing substances","Improves antibody detection sensitivity and specificity","Compatible with Luminex-based SAB assays"],
    applications:["Elimination of prozone effect in high-PRA patients","Removal of interfering substances from patient sera","Pre-treatment of samples before SAB antibody testing"],
    specs:{"Method":"Magnetic bead separation","Compatible Assays":"LABScreen™ Single Antigen Class I and II","Sample Treatment":"Pre-incubation step","Regulatory":"RUO"},
   },

  { id:"ol-lat", name:"Lambda Antigen Tray (LAT™)", brand:"onelambda", category:"transplant", subcategory:"ELISA-Based HLA Antibody Identification",
    description:"ELISA-based Terasaki trays coated with HLA antigens for detecting HLA antibodies and PRA screening.",
    tags:["elisa","hla","transplant","lat"],
    packaging:[{name:"Lambda Antigen Tray",catalogueNumber:"03LATMHD",units:"20 Tests",format:"Terasaki tray"}],
    features:["HLA antigen mixture on each Terasaki tray well","ELISA-based colorimetric detection","No Luminex analyser required","Standard laboratory microplate reader compatible"],
    applications:["HLA antibody PRA screening","Pre-transplant sensitisation assessment","Laboratories without Luminex access"],
    specs:{"Method":"ELISA on Terasaki tray","Format":"Terasaki microdroplet tray","Detection":"Colorimetric ELISA","Equipment":"Standard microplate reader"},
   },

  { id:"ol-lat-mixed", name:"Lambda Antigen Tray Mixed", brand:"onelambda", category:"transplant", subcategory:"ELISA-Based HLA Antibody Identification",
    description:"ELISA Terasaki trays with comprehensive mixture of Class I and Class II HLA antigens for broad antibody screening.",
    tags:["elisa","hla","transplant"],
    packaging:[{name:"Lambda Antigen Tray Mixed",catalogueNumber:"03LATMHD",units:"20 Tests",format:"Terasaki tray"}],
    features:["Mixed Class I and Class II HLA antigens per well","ELISA colorimetric detection","Broad antibody screening in one assay","No dedicated analyser required"],
    applications:["Broad Class I + Class II HLA antibody screening","PRA determination in ELISA-based laboratories"],
    specs:{"Method":"ELISA on Terasaki tray","HLA Coverage":"Mixed Class I and Class II","Format":"Terasaki tray","Equipment":"Microplate reader"},
   },

  { id:"ol-lat-class1", name:"Lambda Antigen Tray™ Class I Single Antigen", brand:"onelambda", category:"transplant", subcategory:"ELISA-Based HLA Antibody Identification",
    description:"ELISA Terasaki trays coated with individual HLA Class I antigens for high-resolution antibody identification in high-PRA patients.",
    tags:["elisa","hla","class-i","transplant"],
    packaging:[{name:"Lambda Antigen Tray Class I Single Antigen",catalogueNumber:"03LAT1HD",units:"20 Tests",format:"Terasaki tray"}],
    features:["Individual HLA Class I antigens per tray well","ELISA detection method","Single-antigen resolution for Class I","No Luminex equipment required"],
    applications:["Class I HLA antibody identification in high-PRA patients","ELISA-based single-antigen antibody testing","Confirmation of Luminex antibody profiles"],
    specs:{"Method":"ELISA on Terasaki tray","HLA Coverage":"Class I single antigen","Format":"Terasaki tray","Equipment":"Microplate reader"},
   },

  { id:"ol-at1r-etar", name:"AT1R and ETAR Non-HLA Antibody Assays", brand:"onelambda", category:"transplant", subcategory:"ELISA-Based Non-HLA Antibody Identification",
    description:"ELISA assays for quantitative determination of anti-AT1R and anti-ETAR antibodies — non-HLA antibodies associated with poor transplant outcomes.",
    tags:["non-hla","at1r","etar","elisa"],
    packaging:[
      {name:"EIA for Anti-AT1R Antibodies",catalogueNumber:"AT1REIA",units:"96 Tests",format:"ELISA plate"},
      {name:"EIA for Anti-ETAR Antibodies",catalogueNumber:"ETAREIA",units:"96 Tests",format:"ELISA plate"},
    ],
    features:["Quantitative ELISA for anti-AT1R antibody determination","Quantitative ELISA for anti-ETAR antibody determination","Validated clinically relevant cut-offs","Standalone 96-well ELISA plate format"],
    applications:["Pre-transplant non-HLA antibody risk assessment","Post-transplant AMR investigation beyond HLA","Research into vascular rejection mechanisms","Comprehensive antibody profiling in sensitised patients"],
    specs:{"Method":"Quantitative ELISA","Targets":"AT1R (Angiotensin II receptor), ETAR (Endothelin receptor)","Format":"96-well ELISA plate","Units":"U/mL","Cut-off":"Validated clinical thresholds","Regulatory":"CE marked"},
   },

  { id:"ol-labscreen-autoantibody", name:"LABScreen™ Autoantibody", brand:"onelambda", category:"transplant", subcategory:"Non-HLA Luminex Based Antibody Identification",
    description:"Luminex-based assay for detecting autoantibodies relevant to transplant outcomes. Complements HLA antibody testing for comprehensive pre-transplant assessment.",
    tags:["autoantibody","non-hla","luminex"],
    packaging:[{name:"LABScreen™ Autoantibody",catalogueNumber:"LSAUTO04",units:"1 Kit",format:"96-well microplate"}],
    features:["Luminex bead-based autoantibody detection","Complements HLA antibody panel testing","Detects clinically relevant non-HLA autoantibodies","Semi-quantitative MFI results"],
    applications:["Comprehensive pre-transplant non-HLA antibody assessment","Post-transplant rejection investigation","Research into autoantibody-mediated graft injury"],
    specs:{"Method":"Luminex xMAP® bead assay","Format":"96-well microplate","Analyzer":"LABScan3D™","Regulatory":"RUO / CE marked (region dependent)"},
   },

  { id:"ol-lambda-cell-trays", name:"Lambda Cell Trays", brand:"onelambda", category:"transplant", subcategory:"Serological-based HLA Antibody Identification",
    description:"Cell-based trays for serological HLA antibody identification using complement-dependent cytotoxicity (CDC) methodology.",
    tags:["cdc","serological","hla"],
    packaging:[{name:"Lambda Cell Trays",catalogueNumber:"LCELL",units:"Varies",format:"Serological tray"}],
    features:["Lymphocyte cell panels on Terasaki trays","Complement-dependent cytotoxicity (CDC) method","Class I expressed on T and B cells; Class II on B cells","Suitable for antibody identification and crossmatch"],
    applications:["Serological HLA antibody identification by CDC","T-cell and B-cell crossmatch testing","Traditional PRA determination using cell panels"],
    specs:{"Method":"Complement-Dependent Cytotoxicity (CDC)","Cell Types":"T and B lymphocytes","Format":"Terasaki tray","Staining":"Fluorescent dye exclusion","Regulatory":"CE marked"},
   },

  // ═══ ONE LAMBDA — MOLECULAR TYPING ═════════════════════════════════════════

  { id:"ol-alltype-ngs", name:"AllType™ NGS HLA Typing Kit", brand:"onelambda", category:"ngs", subcategory:"Next-Generation Sequencing",
    description:"Comprehensive HLA typing across 11 loci in a single amplification and sequencing run. Delivers allele-level, high-resolution HLA typing from 50 ng DNA. Completed on-bench within one workday.", featured:true,
    tags:["hla","typing","ngs","allele-level"],
    highlights:["11-locus typing: A, B, C, DRB1/3/4/5, DQA1, DQB1, DPA1, DPB1","Allele-level phased typing from 50 ng DNA","Illumina® MiSeq and Ion Torrent™ compatible","Turnaround under 24 hours — single workday"],
    features:["Long-range PCR covering full exonic regions","High-resolution phased allele assignment","TypeStream™ Visual software for automated analysis","Scalable 8 to 96 samples per run","CE-IVD marked for in vitro diagnostic use"],
    applications:["Donor and recipient HLA typing for transplantation","Bone marrow / stem cell donor registry typing","High-resolution research typing","Novel allele discovery"],
    specs:{"Loci":"HLA-A,B,C,DRB1,DRB3/4/5,DQA1,DQB1,DPA1,DPB1","Resolution":"Allele-level (4-field, phased)","DNA Input":"50 ng","Platforms":"Illumina® MiSeq, Ion Torrent™","Turnaround":"< 24 hours","Software":"TypeStream™ Visual","Regulatory":"CE-IVD marked"},
    packaging:[
      {name:"AllType™ NGS 8-Sample Kit",catalogueNumber:"OLI8A",units:"8 Samples",format:"NGS amplification kit"},
      {name:"AllType™ NGS 24-Sample Kit",catalogueNumber:"OLI24A",units:"24 Samples",format:"NGS amplification kit"},
      {name:"AllType™ NGS 96-Sample Kit",catalogueNumber:"OLI96A",units:"96 Samples",format:"NGS amplification kit"},
    ],
    relatedProducts:["ol-alltype-fastplex","ol-typestream","ol-labscan3d"] },

  { id:"ol-alltype-fastplex", name:"AllType™ FASTplex™ NGS", brand:"onelambda", category:"ngs", subcategory:"Next-Generation Sequencing",
    description:"Accelerated AllType™ NGS with streamlined amplification for faster turnaround. Optimised for Illumina short-read platforms.",
    tags:["hla","ngs","typing","fast"],
    packaging:[
      {name:"AllType™ FASTplex™ 24-Sample",catalogueNumber:"OLIFPX24A",units:"24 Samples",format:"NGS amplification kit"},
      {name:"AllType™ FASTplex™ 96-Sample",catalogueNumber:"OLIFPX96A",units:"96 Samples",format:"NGS amplification kit"},
    ],
    relatedProducts:["ol-alltype-ngs","ol-typestream"],
    features:["Streamlined amplification protocol — fewer steps than AllType™ NGS","Full 11-locus coverage in one amplification","Illumina short-read sequencing compatible","TypeStream™ Visual software analysis"],
    applications:["High-throughput clinical HLA typing labs","Rapid donor typing for time-critical transplants","Registry typing with accelerated turnaround"],
    specs:{"Loci":"HLA-A,B,C,DRB1,DRB3/4/5,DQA1,DQB1,DPA1,DPB1","Resolution":"Allele-level","Platform":"Illumina short-read","Software":"TypeStream™ Visual","Regulatory":"CE marked"},
   },

  { id:"ol-alltype-rapid", name:"AllType™ Rapid 11 Loci Kit", brand:"onelambda", category:"ngs", subcategory:"Next-Generation Sequencing",
    description:"Rapid 11-loci HLA typing with the same comprehensive coverage as AllType™ NGS in an accelerated workflow.",
    tags:["hla","ngs","rapid","typing"],
    packaging:[{name:"AllType™ Rapid 11 Loci",catalogueNumber:"OLIRAP24A",units:"24 Samples",format:"NGS amplification kit"}],
    features:["11-locus HLA typing in accelerated workflow","Same loci as AllType™ NGS — A,B,C,DRB1/3/4/5,DQA1,DQB1,DPA1,DPB1","Designed for time-critical typing","Illumina sequencing compatible"],
    applications:["Emergency and urgent transplant donor typing","Rapid allele-level typing for living donors","Time-critical registry searches"],
    specs:{"Loci":"11 HLA loci","Resolution":"Allele-level","Platform":"Illumina","Software":"TypeStream™ Visual","Regulatory":"CE marked"},
   },

  { id:"ol-hybritype", name:"One Lambda™ HybriType™ NGS Hybrid Capture Assay", brand:"onelambda", category:"ngs", subcategory:"Next-Generation Sequencing",
    description:"Probe-based NGS hybrid capture for classical HLA, non-classical HLA, MICA/MICB, and ABO blood groups. Full gene or exon coverage with high read balance. Workflow completes in under 5.5 hours.",
    tags:["hla","ngs","hybrid-capture","abo","mica"],
    packaging:[{name:"HybriType™ HLA Plus ABO Flex Kit 96",catalogueNumber:"03HYB18ABOFX",units:"96 Samples",format:"Hybrid capture NGS kit"}],
    relatedProducts:["ol-alltype-ngs","ol-typestream"],
    features:["Probe-based hybrid capture covering full HLA gene regions","Includes classical HLA, non-classical HLA, MICA/MICB, ABO","Highly uniform read coverage across all loci","Workflows complete in under 5.5 hours","Scalable to 96 samples per run"],
    applications:["Comprehensive HLA and ABO typing in single workflow","Research into non-classical HLA and MICA gene variation","High-resolution typing including introns and UTRs","Donor registry full-gene typing"],
    specs:{"Method":"Probe-based NGS hybrid capture","Loci":"Classical HLA + non-classical + MICA/MICB + ABO","Platform":"Illumina","Turnaround":"< 5.5 hours","Samples/Run":"96","Software":"TypeStream™ Visual","Regulatory":"CE marked"},
   },

  { id:"ol-microssp-generic", name:"Micro SSP™ Generic HLA Typing Trays", brand:"onelambda", category:"molecular", subcategory:"Sequence-Specific Primer Typing",
    description:"Ready-to-use lyophilised SSP trays for low-to-intermediate resolution HLA typing of Class I and Class II. Results in under 3 hours using a standard thermocycler.", featured:true,
    tags:["hla","ssp","typing","class-i","class-ii"],
    packaging:[
      {name:"Micro SSP™ Generic Class I Tray",catalogueNumber:"MSSPA004",units:"10 Trays",format:"96-well SSP tray"},
      {name:"Micro SSP™ Generic Class II Tray",catalogueNumber:"MSSPA2004",units:"10 Trays",format:"96-well SSP tray"},
    ],
    relatedProducts:["ol-microssp-highres","ol-alltype-ngs"],
    features:["Lyophilised SSP primer mixes in ready-to-use 96-well tray","Standard PCR thermocycler compatible — no specialist equipment","Agarose gel electrophoresis readout","UniMatch™ software for automated interpretation","Room-temperature lyophilised storage"],
    applications:["Routine transplant donor and recipient HLA typing","Low-to-intermediate resolution clinical typing","Confirmatory typing following serological or SSO screening","Laboratories without NGS capability"],
    specs:{"Method":"Sequence-Specific Primer (SSP) PCR","Resolution":"Low to intermediate","Equipment":"Standard thermocycler + gel electrophoresis","Result Time":"< 3 hours","Storage":"Room temperature (lyophilised)","Software":"UniMatch™"},
   },

  { id:"ol-microssp-highres", name:"Micro SSP™ High Resolution Typing Trays", brand:"onelambda", category:"molecular", subcategory:"Sequence-Specific Primer Typing",
    description:"High-resolution SSP trays for allele-level discrimination at critical HLA loci, suitable for cases requiring greater resolution than generic trays.",
    tags:["hla","ssp","typing","high-resolution"],
    packaging:[
      {name:"Micro SSP™ HLA-A High Resolution",catalogueNumber:"MSSHRESA",units:"10 Trays",format:"96-well SSP tray"},
      {name:"Micro SSP™ HLA-B High Resolution",catalogueNumber:"MSSHRESB",units:"10 Trays",format:"96-well SSP tray"},
      {name:"Micro SSP™ HLA-DRB High Resolution",catalogueNumber:"MSSHRDRB",units:"10 Trays",format:"96-well SSP tray"},
    ],
    relatedProducts:["ol-microssp-generic"],
    features:["Allele-level discriminating primer sets","Higher resolution than generic SSP trays","Ready-to-use lyophilised format","Standard thermocycler compatible","Gel electrophoresis readout"],
    applications:["High-resolution HLA allele discrimination","Resolving low-resolution typing ambiguities","Confirmatory typing following generic SSP","Specific locus high-resolution typing"],
    specs:{"Method":"High-resolution SSP PCR","Resolution":"High (allele-level discrimination)","Equipment":"Standard thermocycler + gel electrophoresis","Loci":"HLA-A, B, DRB1 (locus specific kits)","Storage":"Room temperature (lyophilised)"},
   },

  { id:"ol-bulk-primers", name:"Bulk Primer Sets", brand:"onelambda", category:"molecular", subcategory:"Sequence-Specific Primer Typing",
    description:"Individual HLA SSP primer sets in bulk format for large-scale typing or custom panel configuration.",
    tags:["ssp","primers","typing"],
    packaging:[{name:"Bulk Primer Set",catalogueNumber:"BULKPRIM",units:"Varies",format:"Individual primer sets"}],
    features:["Individual SSP primer sets in bulk quantities","Custom panel configuration possible","Suitable for high-volume typing laboratories","Quality-controlled primer pairs"],
    applications:["Large-scale HLA typing programmes","Custom panel configuration for specific loci","High-throughput typing centre workflows"],
    specs:{"Method":"SSP PCR","Format":"Individual bulk primer sets","Quantity":"Varies by order","Compatibility":"Standard PCR equipment"},
   },

  { id:"ol-labtype-sso", name:"LABType™ SSO HLA Typing", brand:"onelambda", category:"molecular", subcategory:"Reverse SSO Typing",
    description:"Reverse sequence-specific oligonucleotide (rSSO) typing using Luminex xMAP® beads. Intermediate-to-high resolution HLA typing compatible with LABScan3D™ and LABScan™ 100.", featured:true,
    tags:["hla","sso","typing","luminex"],
    highlights:["Intermediate-to-high resolution HLA typing","Luminex xMAP® bead-based rSSO method","Compatible with LABScan3D™ and LABScan™ 100","Fast 6-hour turnaround"],
    features:[
      "Reverse SSO hybridisation on Luminex xMAP® bead arrays",
      "Biotinylated PCR product hybridises to bead-bound SSO probes",
      "Streptavidin-PE detection for high sensitivity",
      "Automated analysis with HLA Fusion™ software",
      "High-throughput 96-well microplate format",
      "Reproducible lot-to-lot performance",
    ],
    applications:[
      "Donor and recipient HLA typing for solid organ transplantation",
      "Haematopoietic stem cell donor typing",
      "Intermediate-resolution HLA typing for clinical labs",
      "Complement to NGS or SBT for confirmation typing",
    ],
    specs:{"Method":"Reverse SSO (rSSO) on Luminex xMAP® beads","Resolution":"Intermediate to high","Analyzer":"LABScan3D™, LABScan™ 100","Turnaround":"6 hours","Format":"96-well microplate","Software":"HLA Fusion™","Regulatory":"CE marked"},
    packaging:[
      {name:"LABType™ SSO HLA-A",catalogueNumber:"LABTYPA04",units:"1 Kit",format:"96-well microplate"},
      {name:"LABType™ SSO HLA-B",catalogueNumber:"LABTYPB04",units:"1 Kit",format:"96-well microplate"},
      {name:"LABType™ SSO HLA-C",catalogueNumber:"LABTYPCC04",units:"1 Kit",format:"96-well microplate"},
      {name:"LABType™ SSO HLA-DRB1",catalogueNumber:"LABTYPDRB04",units:"1 Kit",format:"96-well microplate"},
      {name:"LABType™ SSO HLA-DQB1",catalogueNumber:"LABTYPD04",units:"1 Kit",format:"96-well microplate"},
    ],
    relatedProducts:["ol-labtype-ancillary","ol-labscan3d","ol-alltype-ngs"] },

  { id:"ol-labtype-ancillary", name:"LABType™ Ancillary Reagents", brand:"onelambda", category:"molecular", subcategory:"Reverse SSO Typing",
    description:"Supporting reagents for LABType™ SSO assays: DNA denaturation reagent, hybridisation buffer, and wash reagents.",
    tags:["ancillary","labtype","sso"],
    packaging:[{name:"LABType™ Ancillary Kit",catalogueNumber:"LABTYP-ANC",units:"1 Kit",format:"Ancillary reagents"}],
    features:["DNA denaturation reagent for rSSO hybridisation","Hybridisation buffer for bead-probe binding","Wash reagents for background reduction","Pre-validated for use with LABType™ SSO kits"],
    applications:["Essential workflow reagents for LABType™ SSO typing","Standardising rSSO protocol across runs","Quality-controlled components for laboratory accreditation"],
    specs:{"Components":"Denaturation reagent, hybridisation buffer, wash buffer","Compatibility":"LABType™ SSO all loci kits","Storage":"2–8 °C"},
   },

  { id:"ol-secore-sbt", name:"SeCore™ SBT HLA Typing Kits", brand:"onelambda", category:"molecular", subcategory:"Sequence Based Typing",
    description:"Sequence-based typing (SBT) kits for high-resolution allele-level HLA genotyping using Sanger sequencing — the gold standard for unambiguous allele assignment.",
    tags:["hla","sbt","typing","sanger"],
    packaging:[
      {name:"SeCore™ SBT HLA-A",catalogueNumber:"SECSBT-A",units:"1 Kit",format:"SBT amplification kit"},
      {name:"SeCore™ SBT HLA-B",catalogueNumber:"SECSBT-B",units:"1 Kit",format:"SBT amplification kit"},
      {name:"SeCore™ SBT HLA-DRB1",catalogueNumber:"SECSBT-DRB",units:"1 Kit",format:"SBT amplification kit"},
    ],
    features:["Long-range PCR amplification of HLA exons 2 and 3 (Class I) and exon 2 (Class II)","Sanger sequencing-based allele assignment","Group-specific primers minimise ambiguity","SeqA™ analysis software for automated allele calling","Validated against IMGT/HLA database"],
    applications:["High-resolution allele-level HLA typing","Unambiguous allele assignment for complex cases","Confirmatory typing in transplant and registry programmes","Novel allele sequencing and characterisation"],
    specs:{"Method":"Sequence-Based Typing (SBT) — Sanger sequencing","Resolution":"Allele-level","Sequencing":"Standard capillary electrophoresis (Sanger)","Software":"SeqA™","Regulatory":"CE marked"},
   },

  { id:"ol-secore-gssp", name:"SeCore™ GSSP Kit", brand:"onelambda", category:"molecular", subcategory:"Sequence Based Typing",
    description:"Group-specific sequencing primer (GSSP) kits for resolving HLA sequence ambiguities during SBT typing.",
    tags:["hla","sbt","gssp","ambiguity"],
    packaging:[{name:"SeCore™ GSSP Kit",catalogueNumber:"SECGSSP04",units:"1 Kit",format:"GSSP primers"}],
    features:["Group-specific sequencing primer sets","Resolves sequence ambiguities from standard SBT","Compatible with standard Sanger sequencing instruments","Validated allele-specific primer designs"],
    applications:["Resolution of ambiguous allele combinations from SBT","Confirmation of novel or unusual alleles","Reducing homozygous allele ambiguities","High-resolution typing in complex cases"],
    specs:{"Method":"Group-Specific Sequencing Primer (GSSP) PCR + Sanger sequencing","Application":"Ambiguity resolution for SBT","Equipment":"Standard Sanger sequencer","Regulatory":"CE marked"},
   },

  { id:"ol-linkseq-hla-kir", name:"LinkSēq™ HLA and KIR Typing Kits", brand:"onelambda", category:"molecular", subcategory:"LinkSeq Real-Time PCR",
    description:"Real-time PCR kits for rapid presence/absence testing of HLA and KIR genes.",
    tags:["hla","kir","real-time-pcr","typing"],
    packaging:[
      {name:"LinkSēq HLA Typing Kit",catalogueNumber:"LSEQ-HLA",units:"1 Kit",format:"Real-time PCR kit"},
      {name:"LinkSēq KIR Typing Kit",catalogueNumber:"LSEQ-KIR",units:"1 Kit",format:"Real-time PCR kit"},
    ],
    features:["Real-time PCR presence/absence testing for HLA genes","KIR gene content typing by real-time PCR","Allelic discrimination probes for rapid genotyping","Standard real-time PCR instrument compatible","Fast 2–4 hour workflow"],
    applications:["HLA gene presence/absence typing for clinical and research use","KIR genotyping for NK cell biology and transplant outcome prediction","Haplogroup determination and population studies","High-throughput gene content screening"],
    specs:{"Method":"Real-time PCR","Targets":"HLA genes, KIR genes","Equipment":"Standard real-time PCR thermocycler","Turnaround":"2–4 hours","Regulatory":"CE marked"},
   },

  { id:"ol-linkseq-hpa-abo", name:"LinkSēq™ HPA and ABO Typing Kits", brand:"onelambda", category:"molecular", subcategory:"LinkSeq Real-Time PCR",
    description:"Real-time PCR kits for Human Platelet Antigen (HPA) and ABO blood group genotyping.",
    tags:["hpa","abo","real-time-pcr"],
    packaging:[
      {name:"LinkSēq HPA Typing Kit",catalogueNumber:"LSEQ-HPA",units:"1 Kit",format:"Real-time PCR kit"},
      {name:"LinkSēq ABO Typing Kit",catalogueNumber:"LSEQ-ABO",units:"1 Kit",format:"Real-time PCR kit"},
    ],
    features:["Real-time PCR allelic discrimination for HPA genotyping","ABO blood group genotyping by allele-specific real-time PCR","Fast 2–4 hour workflow","Standard real-time PCR equipment compatible"],
    applications:["Human Platelet Antigen (HPA) typing for transfusion medicine","ABO blood group genotyping for transplant and transfusion","Foetal/neonatal alloimmune thrombocytopenia (FNAIT) workup","Platelet matching for refractory patients"],
    specs:{"Method":"Real-time PCR allelic discrimination","Targets":"HPA antigens, ABO blood group alleles","Equipment":"Standard real-time PCR thermocycler","Turnaround":"2–4 hours","Regulatory":"CE marked"},
   },

  { id:"ol-linkseq-ancillary", name:"LinkSēq™ Ancillary Products", brand:"onelambda", category:"molecular", subcategory:"LinkSeq Real-Time PCR",
    description:"Supporting reagents for LinkSēq real-time PCR typing workflows.",
    tags:["ancillary","linkseq","pcr"],
    packaging:[{name:"LinkSēq Ancillary Kit",catalogueNumber:"LSEQ-ANC",units:"1 Kit",format:"Ancillary"}],
    features:["Positive and negative controls for real-time PCR runs","Standardised master mix components","Validated reagent lots for reproducible results"],
    applications:["Quality control for LinkSēq real-time PCR assays","Workflow standardisation","Accreditation and proficiency support"],
    specs:{"Components":"Controls, master mix components","Compatibility":"All LinkSēq typing kits"},
   },

  { id:"ol-cytokine-genotyping", name:"Cytokine Genotyping Kits", brand:"onelambda", category:"molecular", subcategory:"Non-HLA Genotyping",
    description:"Kits for genotyping cytokine gene polymorphisms relevant to transplant rejection and immune response.",
    tags:["cytokine","genotyping","non-hla"],
    packaging:[{name:"Cytokine Genotyping Kit",catalogueNumber:"CYTOKGENO",units:"1 Kit",format:"SSP typing"}],
    features:["SSP-based genotyping of cytokine gene polymorphisms","Covers TNF-α, IL-10, IL-6, IFN-γ and other clinically relevant cytokines","Ready-to-use tray format","Standard thermocycler and gel system required"],
    applications:["Pre-transplant cytokine gene polymorphism profiling","Research into cytokine-mediated graft rejection","Immunogenetics research in inflammatory conditions","Prediction of immune response post-transplant"],
    specs:{"Method":"SSP PCR","Targets":"TNF-α, IL-10, IL-6, IFN-γ and others","Equipment":"Standard thermocycler + gel electrophoresis","Regulatory":"RUO"},
   },

  { id:"ol-hna-genotyping", name:"HNA Genotyping", brand:"onelambda", category:"molecular", subcategory:"Non-HLA Genotyping",
    description:"Human Neutrophil Antigen (HNA) genotyping for transfusion medicine and transplant applications.",
    tags:["hna","genotyping","non-hla"],
    packaging:[{name:"HNA Genotyping Kit",catalogueNumber:"HNAGENO",units:"1 Kit",format:"SSP typing"}],
    features:["SSP-based genotyping for HNA-1a, 1b, 1c, 2a, 3a, 4a, 5a","Ready-to-use tray format","Standard thermocycler compatible","Validated for clinical transfusion medicine use"],
    applications:["HNA typing for granulocyte transfusion compatibility","FNAGT (foetal/neonatal alloimmune granulocytopenia) workup","Granulocyte donor selection","Transfusion medicine and immunogenetics research"],
    specs:{"Method":"SSP PCR","Targets":"HNA-1a,1b,1c,2a,3a,4a,5a","Equipment":"Standard thermocycler","Regulatory":"CE marked"},
   },

  { id:"ol-kir-sso", name:"KIR SSO Genotyping", brand:"onelambda", category:"molecular", subcategory:"Non-HLA Genotyping",
    description:"SSO genotyping for Killer Immunoglobulin-like Receptor (KIR) genes — critical for NK cell biology and transplant outcomes.",
    tags:["kir","sso","genotyping"],
    packaging:[{name:"KIR SSO Genotyping Kit",catalogueNumber:"KIRSSO04",units:"1 Kit",format:"Luminex bead kit"}],
    features:["rSSO typing on Luminex xMAP® beads for KIR gene content","Covers KIR2DL1-3, KIR2DS1-5, KIR3DL1-3, KIR3DS1, and others","High-throughput 96-well microplate format","HLA Fusion™ software compatible"],
    applications:["KIR gene content typing for HSCT donor selection","NK cell biology and KIR-HLA interaction research","Population genetics and KIR haplotype studies","Post-transplant NK cell reconstitution monitoring"],
    specs:{"Method":"Reverse SSO on Luminex xMAP® beads","KIR Genes":"KIR2DL1-3, KIR2DS1-5, KIR3DL1-3, KIR3DS1 and others","Analyzer":"LABScan3D™","Format":"96-well microplate","Regulatory":"CE marked"},
   },

  { id:"ol-qubit", name:"Qubit™ Fluorometric Quantitation", brand:"onelambda", category:"equipment", subcategory:"Molecular Biology Instrumentation",
    description:"Fluorometric DNA quantitation system for accurate DNA concentration measurement before NGS library preparation.",
    tags:["dna-quantitation","fluorometric","qubit"],
    packaging:[
      {name:"Qubit™ dsDNA HS Assay Kit",catalogueNumber:"Q32851",units:"100 Assays",format:"Fluorometric assay"},
      {name:"Qubit™ dsDNA BR Assay Kit",catalogueNumber:"Q32850",units:"100 Assays",format:"Fluorometric assay"},
    ],
    features:["Fluorometric quantitation using intercalating dyes","dsDNA HS (High Sensitivity) and BR (Broad Range) assay options","Highly accurate — unaffected by RNA or free nucleotide contamination","Compatible with Qubit™ 4 Fluorometer","Minimal sample volume required (1–20 µL)"],
    applications:["DNA quantitation before NGS library preparation","Quality control of DNA extractions","Quantitation of AllType™ NGS and HybriType™ inputs","Verification of library concentrations pre-sequencing"],
    specs:{"Method":"Fluorometric quantitation","Sensitivity":"HS: 10 pg/µL – 100 ng/µL; BR: 2 ng/µL – 1 µg/µL","Sample Volume":"1–20 µL","Instrument":"Qubit™ 4 Fluorometer","Dye":"Proprietary intercalating fluorescent dye"},
   },

  { id:"ol-veritiPro", name:"VeritiPro™ Thermal Cycler", brand:"onelambda", category:"equipment", subcategory:"Molecular Biology Instrumentation",
    description:"High-performance thermal cycler compatible with Micro SSP™, SeCore™, and all PCR-based One Lambda typing assays.",
    tags:["thermal-cycler","pcr","instrumentation"],
    packaging:[{name:"VeritiPro™ 96-Well Thermal Cycler",catalogueNumber:"A48138",units:"1 Instrument",format:"Thermal cycler"}],
    features:["Gradient thermal block system for optimised PCR","12 independent temperature blocks for flexibility","Fast ramp rates for efficient cycling","Compatible with all One Lambda SSP and SBT kits","Intuitive touchscreen interface"],
    applications:["PCR amplification for Micro SSP™ HLA typing","PCR for SeCore™ SBT HLA genotyping","Research PCR amplification applications","Batch processing of multiple sample types simultaneously"],
    specs:{"Format":"96-well block thermal cycler","Blocks":"12 independent zones","Ramp Rate":"Up to 6°C/sec","Volume Range":"10–100 µL","Temperature Range":"0–100°C","Interface":"Touchscreen","Footprint":"Compact benchtop"},
   },

  // ═══ ONE LAMBDA — SEROLOGICAL TYPING ═══════════════════════════════════════

  { id:"ol-terasaki-trays", name:"Terasaki HLA Tissue Typing Trays", brand:"onelambda", category:"serological", subcategory:"HLA Tissue Typing Trays",
    description:"Complement-dependent cytotoxicity (CDC) Terasaki trays for serological HLA tissue typing — the classic method for pre-transplant crossmatch and HLA antigen identification.", featured:true,
    tags:["serological","cdc","terasaki","hla","tissue-typing"],
    highlights:["Classic CDC method for HLA tissue typing","Class I and Class II formats available","72-well tray format","High antigen coverage"],
    packaging:[
      {name:"Terasaki HLA Class II Tissue Typing Tray, 72 Well",catalogueNumber:"O3DR72",units:"10 Trays",format:"72-well format"},
      {name:"Terasaki HLA Class II Dry Tissue Typing Tray",catalogueNumber:"O3DR72D",units:"10 Trays",format:"72-well format"},
      {name:"Terasaki Special Class I Tissue Typing Set",catalogueNumber:"O3TM144",units:"20 Tests",format:""},
    ],
    relatedProducts:["ol-terasaki-supplement","ol-lmt"],
    features:["Human lymphocyte panels from selected donors","Represents broad range of HLA-A, B, C and DR, DQ specificities","72-well Terasaki microtitre tray format","Ready-to-use cryopreserved cells","Lot-to-lot consistency testing"],
    applications:["HLA antigen typing by CDC","Pre-transplant crossmatch testing","Panel Reactive Antibody (PRA) determination using cell panels","Quality control in serological HLA laboratories"],
    specs:{"Method":"Complement-Dependent Cytotoxicity (CDC)","Format":"72-well Terasaki tray","Cell Types":"T lymphocytes (Class I), B lymphocytes (Class II)","Storage":"Liquid nitrogen","HLA Coverage":"Representative A, B, C, DR, DQ specificities","Regulatory":"CE marked"},
   },

  { id:"ol-terasaki-supplement", name:"Terasaki Supplement HLA Tissue Typing Trays", brand:"onelambda", category:"serological", subcategory:"HLA Tissue Typing Trays",
    description:"Supplementary Terasaki trays with additional HLA specificities to extend the standard typing panel.",
    tags:["serological","cdc","terasaki","supplement"],
    packaging:[{name:"Terasaki Supplement Tray",catalogueNumber:"O3SUPPL",units:"10 Trays",format:"72-well format"}],
    relatedProducts:["ol-terasaki-trays"],
    features:["Additional specificities extending standard typing panels","Terasaki 72-well tray format","Cryopreserved cell panels with validated HLA typing","Complements standard ASHI/EFI panel requirements"],
    applications:["Extending antibody identification panel coverage","Typing rare or unusual HLA specificities","Supplementing standard CDC crossmatch panels"],
    specs:{"Method":"Complement-Dependent Cytotoxicity (CDC)","Format":"72-well Terasaki tray","Coverage":"Supplemental HLA specificities","Storage":"Liquid nitrogen","Regulatory":"CE marked"},
   },

  { id:"ol-lmt", name:"Lambda Monoclonal Trays (LMT™)", brand:"onelambda", category:"serological", subcategory:"HLA Tissue Typing Trays",
    description:"Trays containing highly specific monoclonal antibodies for accurate HLA antigen identification by CDC. Greater specificity than polyclonal antisera.",
    tags:["serological","monoclonal","cdc","hla"],
    packaging:[{name:"Lambda Monoclonal Trays (LMT)",catalogueNumber:"LMTMONO",units:"10 Trays",format:"Serological tray"}],
    relatedProducts:["ol-terasaki-trays"],
    features:["Monoclonal antibodies with defined HLA specificity","Greater lot-to-lot consistency than polyclonal antisera","Pre-titrated working dilutions","Validated against international HLA standards"],
    applications:["HLA antigen identification by CDC in serological typing","Quality control reference typing in HLA laboratories","Confirmation of HLA antigen assignments from other methods"],
    specs:{"Type":"Monoclonal antibody panels","Method":"CDC (Terasaki)","Format":"Serological tray","Specificity":"Validated against reference cells","Regulatory":"CE marked"},
   },

  { id:"ol-b27-antibody", name:"B27 Monoclonal Antibody", brand:"onelambda", category:"serological", subcategory:"Serological Reagents",
    description:"Highly specific monoclonal antibody for HLA-B27 antigen identification — key marker for ankylosing spondylitis and HLA-B27 associated disorders.",
    tags:["b27","monoclonal","serological"],
    highlights:["Highly specific for HLA-B27 antigen","For serological typing by CDC or flow cytometry","Ready-to-use format","Quality-controlled for specificity and titre"],
    features:["Monoclonal antibody with defined HLA-B27 specificity","Suitable for complement-dependent cytotoxicity (CDC) testing","Compatible with standard Terasaki microdroplet method","Pre-titrated and quality-controlled"],
    applications:["HLA-B27 antigen identification in transplant workup","Ankylosing spondylitis and related HLA-B27 disease association testing","Quality control in serological HLA typing panels","Research into HLA-B27 associated autoimmune conditions"],
    specs:{"Target":"HLA-B27 antigen","Antibody Type":"Monoclonal","Method":"CDC (Terasaki) or flow cytometry","Format":"Ready-to-use","Storage":"2–8 °C"},
    packaging:[{name:"B27 Monoclonal Antibody",catalogueNumber:"B27MONO",units:"1 Vial",format:"Monoclonal antibody"}] },

  { id:"ol-cytotoxic-controls", name:"Cytotoxic Controls", brand:"onelambda", category:"serological", subcategory:"Serological Reagents",
    description:"Positive and negative cytotoxic control sera for quality assurance in CDC crossmatch testing.",
    tags:["cdc","controls","serological"],
    packaging:[
      {name:"Positive Cytotoxic Control",catalogueNumber:"CYTPOS",units:"1 Vial",format:"Control serum"},
      {name:"Negative Cytotoxic Control",catalogueNumber:"CYTNEG",units:"1 Vial",format:"Control serum"},
    ],
    features:["Positive control: validated to produce ≥80% lymphocyte killing","Negative control: validated for <10% cell death","Lot-to-lot consistency guaranteed","Compatible with standard CDC crossmatch protocols"],
    applications:["Daily QC in CDC crossmatch testing","Accreditation and proficiency requirements","Validation of cytotoxicity assay performance"],
    specs:{"Components":"Positive cytotoxic control serum, Negative control serum","Method":"CDC cytotoxicity assay","Expected Result":"Positive: ≥80% killing; Negative: <10%","Storage":"−20 °C","Regulatory":"CE marked"},
   },

  { id:"ol-dynabeads", name:"Dynabeads™ for Cell Isolation", brand:"onelambda", category:"serological", subcategory:"Serological Reagents",
    description:"Magnetic bead reagents for isolating T and B lymphocytes for use in CDC crossmatch assays.",
    tags:["dynabeads","cell-isolation","serological"],
    packaging:[
      {name:"Dynabeads™ Pan T (CD2)",catalogueNumber:"DYNAPAT",units:"1 Vial",format:"Magnetic beads"},
      {name:"Dynabeads™ Pan B (CD19)",catalogueNumber:"DYNAPAB",units:"1 Vial",format:"Magnetic beads"},
    ],
    features:["Magnetic beads coated with anti-CD2 (Pan T) or anti-CD19 (Pan B)","Rapid magnetic isolation — no centrifugation","High purity T or B lymphocyte populations","Compatible with standard magnet and tubes"],
    applications:["T-lymphocyte isolation for T-cell CDC crossmatch","B-lymphocyte isolation for B-cell CDC crossmatch","Cell separation prior to flow cytometry crossmatch","Purification of lymphocyte populations from peripheral blood"],
    specs:{"Targets":"CD2 (Pan T cells), CD19 (Pan B cells)","Method":"Magnetic bead separation","Purity":">95% target cell population","Equipment":"Standard magnetic separator","Storage":"2–8 °C","Regulatory":"CE marked"},
   },

  { id:"ol-fluoroquench", name:"FluoroQuench™ Staining/Quenching Reagent", brand:"onelambda", category:"serological", subcategory:"Serological Reagents",
    description:"Fluorescent quenching reagent for differentiating live from dead cells in CDC crossmatch assays.",
    tags:["fluoroquench","cdc","staining"],
    packaging:[{name:"FluoroQuench™",catalogueNumber:"FLUROQUENCH",units:"1 Vial",format:"Reagent"}],
    features:["Fluorescent dye for live/dead cell discrimination in CDC","Quenches background fluorescence in dead cells","Optimised for Terasaki microdroplet CDC method","Compatible with standard fluorescence microscopy"],
    applications:["Live/dead cell discrimination in CDC crossmatch assays","Enhanced reading of CDC results by fluorescence microscopy","Standard serological HLA typing CDC protocols"],
    specs:{"Method":"Fluorescence-based live/dead staining","Excitation/Emission":"Compatible with standard fluorescence microscope filters","Volume":"Ready-to-use","Storage":"2–8 °C, protect from light"},
   },

  { id:"ol-bulk-monoclonal", name:"Bulk Monoclonal Antibody", brand:"onelambda", category:"serological", subcategory:"Serological Reagents",
    description:"Bulk monoclonal antibodies for HLA antigen identification in high-throughput serological laboratories.",
    tags:["monoclonal","bulk","serological"],
    packaging:[{name:"Bulk Monoclonal Antibody",catalogueNumber:"BULKMONO",units:"Varies",format:"Bulk antibody"}],
    features:["Large-volume monoclonal antibody format for high-throughput labs","Defined HLA specificity and titre","Suitable for large-scale typing programmes","Quality-controlled batches"],
    applications:["High-volume HLA serological typing","Typing centre bulk processing","Production of custom typing panels"],
    specs:{"Type":"Monoclonal antibodies against HLA antigens","Format":"Bulk vials","Application":"CDC-based serological typing","Regulatory":"CE marked"},
   },

  // ═══ ONE LAMBDA — INSTRUMENTS & SOFTWARE ═══════════════════════════════════

  { id:"ol-labscan3d", name:"LABScan3D™ Multiplex Analyzer", brand:"onelambda", category:"multiplex", subcategory:"Readers & Analysers",
    description:"One Lambda's flagship multiplex flow analyser purpose-built for transplant diagnostics. Reads Luminex xMAP® beads to deliver high-resolution HLA antibody identification and typing.", featured:true,
    tags:["analyzer","hla","transplant","luminex","instrument"],
    highlights:["500-plex xMAP® bead technology","FDA 510(k) cleared, CE marked","Integrated with HLA Fusion™ software","Compatible with all LABScreen™ and LABType™ kits"],
    features:["Three-laser optical system with 10 fluorescent channels","Automated data acquisition via LABScan3D™ Manager software","Built-in barcode reader for sample tracking","Compatible with 96-well microplates"],
    applications:["HLA antibody detection using LABScreen™ assays","HLA typing using LABType™ SSO kits","Post-transplant DSA monitoring","Virtual crossmatch support"],
    specs:{"Bead Regions":"500","Lasers":"3 (Red 633nm, Green 532nm, Violet 405nm)","Fluorescent Channels":"10","Sample Throughput":"Up to 96 samples per run","Plate Format":"Standard 96-well microplate","Regulatory Status":"FDA 510(k) cleared, CE marked"},
    packaging:[{name:"LABScan3D™ Analyzer",catalogueNumber:"LABScan3D",units:"1 Instrument",format:"Benchtop analyser"}],
    relatedProducts:["ol-labscreen-sa1","ol-labscreen-sa2","ol-labtype-sso","ol-fusion"] },

  { id:"ol-labscan100", name:"LABScan™ 100 Analyser", brand:"onelambda", category:"multiplex", subcategory:"Readers & Analysers",
    description:"Entry-level Luminex bead reader for lower-throughput laboratories. Compatible with all One Lambda Luminex-based assays.",
    tags:["analyzer","luminex","instrument"],
    packaging:[{name:"LABScan™ 100",catalogueNumber:"LABScan100",units:"1 Instrument",format:"Benchtop analyser"}],
    relatedProducts:["ol-labscan3d"],
    features:["Luminex 100/200-compatible bead reader","Reads all One Lambda Luminex-based assays","Software-controlled data acquisition","Suitable for lower-throughput laboratories","Compact benchtop form factor"],
    applications:["HLA antibody detection with LABScreen™ assays","HLA typing with LABType™ SSO kits","Entry-level multiplex bead reading in transplant labs"],
    specs:{"Platform":"Luminex 100/200 compatible","Bead Regions":"Up to 100","Lasers":"2 (Red 633nm, Green 532nm)","Throughput":"Up to 96 samples/run","Software":"LABScan™ Manager","Regulatory":"FDA 510(k) cleared, CE marked"},
   },

  { id:"ol-fusion", name:"HLA Fusion™ Software", brand:"onelambda", category:"transplant", subcategory:"Software",
    description:"Comprehensive laboratory information and analysis software for transplant diagnostics. Integrates LABScreen™ antibody assays, LABType™ typing, and LABScan3D™ data into a single workflow.",
    tags:["software","hla","transplant","lims"],
    highlights:["Centralised analysis for all One Lambda assays","Virtual crossmatch module","HL7 bidirectional LIS/HIS interface","21 CFR Part 11 compliant audit trail"],
    specs:{"Platform":"Windows desktop application","LIS Interface":"HL7 bidirectional","Compliance":"21 CFR Part 11"},
    packaging:[{name:"HLA Fusion™ Software",catalogueNumber:"HLAFusion4",units:"1 License",format:"Software license"}],
    relatedProducts:["ol-labscan3d","ol-labscreen-sa1"] },

  { id:"ol-typestream", name:"TypeStream™ Visual NGS Analysis Software", brand:"onelambda", category:"ngs", subcategory:"Software",
    description:"Intelligent standalone software for AllType™ NGS and HybriType™ data analysis. Automates processing of Illumina FASTQ and Ion Torrent BAM files with quality metrics and reporting.",
    tags:["software","ngs","analysis","hla"],
    packaging:[{name:"TypeStream™ Visual Software",catalogueNumber:"TYPESTREAM",units:"1 License",format:"Software license"}],
    relatedProducts:["ol-alltype-ngs","ol-alltype-fastplex"],
    features:["Automated FASTQ (Illumina) and BAM (Ion Torrent) file analysis","Allele-level phased HLA genotype assignment","Quality score-based filtering of sequencing reads","Integrated QC metrics and run reporting","Exports to HLA Fusion™ for review and LIMS integration"],
    applications:["NGS analysis for AllType™ and AllType™ FASTplex™ assays","NGS analysis for HybriType™ hybrid capture data","Automated high-throughput typing result generation","Bioinformatics pipeline for HLA NGS data"],
    specs:{"Platform":"Windows standalone software","Compatible Sequencers":"Illumina (FASTQ), Ion Torrent (BAM)","Compatible Assays":"AllType™ NGS, FASTplex™, HybriType™","Output":"Phased allele-level genotypes","Export":"HLA Fusion™, CSV, PDF","Regulatory":"CE-IVD"},
   },

  { id:"ol-hla-pro", name:"One Lambda™ HLA PRO Automated Pipettor", brand:"onelambda", category:"equipment", subcategory:"Automated Pipettor",
    description:"Automated modular pipetting system for streamlining HLA typing and antibody detection workflows. Accommodates multiple technologies on a single instrument for maximum flexibility.",
    tags:["automation","pipettor","instrument"],
    packaging:[{name:"One Lambda™ HLA PRO",catalogueNumber:"HLA-PRO",units:"1 Instrument",format:"Automated pipettor"}],
    relatedProducts:["ol-labscan3d","ol-labtype-sso"],
    features:["Automated pipetting for Micro SSP™, LABType™ SSO, and LABScreen™ workflows","Modular design accommodates different plate formats","Reduces manual pipetting errors","Pre-programmed protocols for One Lambda kits","Barcode-driven sample tracking"],
    applications:["Automated sample loading for HLA typing assays","High-throughput HLA laboratory automation","Error reduction in antibody detection pipetting","Standardisation of repetitive liquid handling steps"],
    specs:{"Type":"Automated modular pipettor","Compatible Assays":"Micro SSP™, LABType™ SSO, LABScreen™ SAB","Plate Format":"96-well microplate and SSP trays","Sample Tracking":"Barcode integrated","Software":"Instrument-specific control software"},
   },

  // ═══ ONE LAMBDA — POST-TRANSPLANT MONITORING ═══════════════════════════════

  { id:"ol-accept-cfdna", name:"One Lambda Devyser Accept cfDNA Assay", brand:"onelambda", category:"posttransplant", subcategory:"Donor-Derived Cell-Free DNA",
    description:"CE-IVD marked NGS solution for monitoring donor-derived cell-free DNA (dd-cfDNA) in solid organ transplant recipients. Enables earlier detection of allograft injury with 0.1% limit of detection.", featured:true,
    tags:["cfdna","post-transplant","ngs","monitoring","allograft"],
    highlights:["0.1% limit of detection — industry-leading sensitivity","All-in-one: PCR amplification, indexing, sequencing-ready library","< 45 minutes hands-on time","CE-IVD marked"],
    specs:{"LOD":"0.1% dd-cfDNA","Method":"50-indel multiplex PCR + NGS","Platforms":"Illumina","Hands-on Time":"< 45 minutes","Workflow":"~1 day","Regulatory":"CE-IVD marked"},
    packaging:[{name:"Devyser Accept cfDNA Assay Kit",catalogueNumber:"ACCEPT-CFDNA",units:"24 Samples",format:"NGS library prep kit"}],
    relatedProducts:["ol-chimerism-ngs","ol-alltype-ngs"],
    features:["50-indel multiplex PCR approach — no donor genotype needed","Sequencing-ready library prep in one workflow","Automated dd-cfDNA quantification by Advyser Solid Organ software","Limit of detection: 0.1% dd-cfDNA","< 45 minutes hands-on time","Validated in kidney, heart, liver and lung transplant"],
    applications:["Non-invasive allograft injury monitoring in solid organ transplant recipients","Early detection of rejection before clinical symptoms","Complement to biopsy and DSA monitoring","Post-transplant surveillance in kidney, heart, lung, and liver transplants"],
   },

  { id:"ol-chimerism-ngs", name:"One Lambda Devyser Chimerism NGS Assay", brand:"onelambda", category:"posttransplant", subcategory:"Chimerism Monitoring",
    description:"NGS-based post-transplant chimerism monitoring for accurate quantification of donor and recipient cell populations after haematopoietic stem cell transplantation.",
    tags:["chimerism","post-transplant","ngs","monitoring"],
    packaging:[{name:"Devyser Chimerism NGS Kit",catalogueNumber:"CHIM-NGS",units:"24 Samples",format:"NGS kit"}],
    relatedProducts:["ol-chimerism","ol-accept-cfdna"],
    features:["NGS-based indel marker approach for chimerism quantification","Higher sensitivity than standard STR capillary methods","Detects minor chimerism down to 0.1%","Automated Advyser Chimerism software analysis","Suitable for myeloid and whole blood chimerism"],
    applications:["Post-HSCT engraftment monitoring","Detection of impending graft failure or relapse","Lineage-specific chimerism analysis","Minimal residual disease (MRD) surrogate marker"],
    specs:{"Method":"NGS-based indel marker chimerism","Sensitivity":"Down to 0.1% minor chimerism","Platform":"Illumina","Software":"Advyser Chimerism","Sample Types":"Whole blood, bone marrow","Regulatory":"CE marked"},
   },

  { id:"ol-chimerism", name:"One Lambda Devyser Chimerism Assay", brand:"onelambda", category:"posttransplant", subcategory:"Chimerism Monitoring",
    description:"PCR-based chimerism monitoring using STR markers for post-transplant engraftment and relapse monitoring.",
    tags:["chimerism","post-transplant","str","monitoring"],
    packaging:[{name:"Devyser Chimerism STR Kit",catalogueNumber:"CHIM-STR",units:"24 Samples",format:"PCR kit"}],
    relatedProducts:["ol-chimerism-ngs"],
    features:["Short tandem repeat (STR) marker panel for chimerism","Compatible with standard capillary electrophoresis systems","Established gold-standard STR chimerism method","Covers informative STR loci for donor/recipient discrimination"],
    applications:["Post-HSCT engraftment monitoring by STR","Donor and recipient chimerism percentage calculation","Relapse detection following allogeneic stem cell transplantation","Lineage-specific chimerism in clinical practice"],
    specs:{"Method":"Short Tandem Repeat (STR) PCR","Detection":"Capillary electrophoresis fluorescence","Sensitivity":"~1–5% minor chimerism","Software":"GeneMapper or equivalent","Regulatory":"CE marked"},
   },

  // ═══ OTHER BRANDS ══════════════════════════════════════════════════════════

  { id:"luminex-magpix", name:"MAGPIX® System", brand:"luminex", category:"multiplex", description:"Compact magnetic-bead multiplex platform delivering up to 50-plex per well.", featured:true, tags:["xmap","compact"], packaging:[{name:"MAGPIX® System",catalogueNumber:"MAGPIX",units:"1 Instrument",format:"Benchtop analyser"}] },
  { id:"luminex-flexmap3d", name:"FLEXMAP 3D® System", brand:"luminex", category:"multiplex", description:"High-throughput xMAP analyzer with 500-plex capability for biomarker discovery.", tags:["xmap","research"] },
  { id:"luminex-intelliflex", name:"xMAP INTELLIFLEX™", brand:"luminex", category:"multiplex", description:"Next-generation flow-based multiplexer with dual reporter channels.", tags:["xmap"] },
  { id:"merck-cd3", name:"Anti-CD3 Monoclonal Antibody", brand:"merck", category:"antibodies", description:"Mouse monoclonal targeting human CD3 — validated for FC, IHC, and WB." },
  { id:"merck-sybr", name:"SYBR® Green qPCR Master Mix", brand:"merck", category:"molecular", description:"Optimized 2× master mix for high-sensitivity real-time PCR.", featured:true },
  { id:"diasorin-liaison-xl", name:"LIAISON® XL Immunoassay Analyzer", brand:"diasorin", category:"immuno", description:"Fully automated chemiluminescent platform with up to 180 tests/hour.", featured:true },
  { id:"diasorin-vitd", name:"LIAISON® Vitamin D Total Assay", brand:"diasorin", category:"immuno", description:"Fully automated 25-OH vitamin D quantification — clinical reference standard." },
  { id:"cytek-aurora", name:"Cytek® Aurora Flow Cytometer", brand:"cytek", category:"flow", description:"Up to 5-laser, 64-color full-spectrum flow cytometer for complex panels.", featured:true },
  { id:"cytek-northernlights", name:"Cytek® Northern Lights™", brand:"cytek", category:"flow", description:"Compact spectral flow cytometer purpose-built for clinical research." },
  { id:"ngene-onco", name:"ONCOaccuPanel™ Pan-Cancer NGS", brand:"ngene", category:"ngs", description:"323-gene targeted panel covering all major solid-tumor biomarkers.", featured:true },
  { id:"hkm-centrifuge", name:"HKM High-Speed Refrigerated Centrifuge", brand:"hkm", category:"equipment", description:"Up to 21,000 × g with ±1 °C temperature control." },
  { id:"hkm-co2", name:"HKM CO₂ Incubator", brand:"hkm", category:"equipment", description:"Direct-heat 170 L incubator with HEPA-filtered chamber." },
  { id:"hkm-bsc", name:"HKM Class II Biosafety Cabinet", brand:"hkm", category:"equipment", description:"Type A2 cabinet with EN-12469 certification for BSL-2 handling." },
  { id:"bl-cd4-pe", name:"PE Anti-Human CD4 (Clone OKT4)", brand:"biolegend", category:"antibodies", description:"PE-conjugated antibody validated for flow cytometry.", featured:true },
  { id:"bl-elisa-max", name:"ELISA MAX™ Standard Set", brand:"biolegend", category:"immuno", description:"Pre-titered antibody pairs for ELISA development across hundreds of analytes." },
];

export function brandById(id: string) { return brands.find(b => b.id === id)!; }
export function categoryById(id: string) { return categories.find(c => c.id === id)!; }
export function productById(id: string) { return products.find(p => p.id === id); }
export function productsByBrand(id: string) { return products.filter(p => p.brand === id); }
export function productsByCategory(id: string) { return products.filter(p => p.category === id); }
export function featuredProducts() { return products.filter(p => p.featured); }
