import {
  Beaker, Microscope, Dna, HeartPulse, TestTube,
  FlaskConical, Cpu, ShieldCheck, Activity, Layers,
} from "lucide-react";

export type Brand = { id: string; name: string; short: string; blurb: string; accent: string; };
export type Category = { id: string; name: string; icon: React.ReactNode; };

export type PackagingVariant = {
  name: string;
  catalogueNumber: string;
  units: string;
  format?: string;
};

export type Product = {
  id: string; name: string; brand: string; category: string;
  subcategory?: string; description: string; featured?: boolean; tags?: string[];
  image?: string;
  highlights?: string[]; features?: string[]; applications?: string[];
  specs?: Record<string, string>; catalogueNumber?: string;
  packaging?: PackagingVariant[];
  relatedProducts?: string[];
};

export const brands: Brand[] = [
  { id: "onelambda", name: "One Lambda (Thermo Fisher Scientific)", short: "One Lambda", blurb: "Global leader in transplant diagnostics — HLA typing, antibody detection, and crossmatch solutions trusted worldwide.", accent: "#D71920" },
  { id: "merck", name: "Merck Sigma-Aldrich", short: "Merck", blurb: "Reagents, antibodies and research chemicals — life-science gold standard.", accent: "#003366" },
  { id: "luminex", name: "Luminex Corp", short: "Luminex", blurb: "xMAP® multiplex assay technology for high-throughput labs.", accent: "#2EA3F2" },
  { id: "diasorin", name: "DiaSorin", short: "DiaSorin", blurb: "Immunoassays and molecular diagnostics powered by LIAISON® systems.", accent: "#0F4C81" },
  { id: "cytek", name: "CytekBio", short: "Cytek", blurb: "Full-spectrum flow cytometry redefining cellular analysis.", accent: "#5E2A84" },
  { id: "ngene", name: "NgeneBio", short: "NgeneBio", blurb: "NGS-based precision oncology diagnostics.", accent: "#00A19A" },
  { id: "hkm", name: "HKM Bio", short: "HKM", blurb: "Reliable laboratory equipment — centrifuges, incubators, and safety cabinets.", accent: "#7A8B99" },
  { id: "biolegend", name: "BioLegend", short: "BioLegend", blurb: "World-class antibodies and reagents for flow cytometry and ELISA.", accent: "#E94B3C" },
];

export const categories: Category[] = [
  { id: "multiplex", name: "Multiplex Analyzers", icon: <Cpu className="h-4 w-4" /> },
  { id: "flow", name: "Flow Cytometers", icon: <Microscope className="h-4 w-4" /> },
  { id: "transplant", name: "Transplant Diagnostics", icon: <HeartPulse className="h-4 w-4" /> },
  { id: "molecular", name: "Molecular Diagnostics", icon: <Dna className="h-4 w-4" /> },
  { id: "immuno", name: "Immunoassays", icon: <ShieldCheck className="h-4 w-4" /> },
  { id: "ngs", name: "NGS / Sequencing", icon: <FlaskConical className="h-4 w-4" /> },
  { id: "antibodies", name: "Antibodies & Reagents", icon: <TestTube className="h-4 w-4" /> },
  { id: "equipment", name: "Lab Equipment & Consumables", icon: <Beaker className="h-4 w-4" /> },
  { id: "serological", name: "Serological Typing", icon: <Activity className="h-4 w-4" /> },
  { id: "posttransplant", name: "Post-Transplant Monitoring", icon: <Layers className="h-4 w-4" /> },
];

// Navigation tree mirroring vhbio.com One Lambda structure exactly
export const oneLambdaNav: Record<string, Record<string, string[]>> = {
  "Antibody Detection": {
    "Luminex-based HLA Antibody Identification": ["ol-labscreen-sa1","ol-labscreen-sa2","ol-labscreen-mixed","ol-labscreen-pra","ol-labscreen-multi","ol-labscreen-mica","ol-labscreen-explex","ol-labscreen-supplement","ol-labscreen-ancillary"],
    "Complement Binding HLA Antibody Identification": ["ol-c1qscreen"],
    "Flow Cytometry Based HLA Antibody Identification": ["ol-flowpra-sa","ol-flowpra-specific","ol-flowpra-ancillary"],
    "Advanced Crossmatch Testing": ["ol-flowdsa-xm"],
    "Advanced Antibody Testing": ["ol-magsort"],
    "ELISA-Based HLA Antibody Identification": ["ol-lat","ol-lat-mixed","ol-lat-class1"],
    "ELISA-Based Non-HLA Antibody Identification": ["ol-at1r-etar"],
    "Non-HLA Luminex Based Antibody Identification": ["ol-labscreen-autoantibody"],
    "Serological-based HLA Antibody Identification": ["ol-lambda-cell-trays"],
  },
  "Molecular Typing": {
    "Next-Generation Sequencing": ["ol-alltype-ngs","ol-alltype-fastplex","ol-alltype-rapid","ol-hybritype"],
    "Sequence-Specific Primer Typing": ["ol-microssp-generic","ol-microssp-highres","ol-bulk-primers"],
    "Reverse SSO Typing": ["ol-labtype-sso","ol-labtype-ancillary"],
    "Sequence Based Typing": ["ol-secore-sbt","ol-secore-gssp"],
    "LinkSeq Real-Time PCR": ["ol-linkseq-hla-kir","ol-linkseq-hpa-abo","ol-linkseq-ancillary"],
    "Non-HLA Genotyping": ["ol-cytokine-genotyping","ol-hna-genotyping","ol-kir-sso"],
    "Molecular Biology Instrumentation": ["ol-qubit","ol-veritiPro"],
  },
  "Serological Typing": {
    "HLA Tissue Typing Trays": ["ol-terasaki-trays","ol-terasaki-supplement","ol-lmt"],
    "Serological Reagents": ["ol-b27-antibody","ol-cytotoxic-controls","ol-dynabeads","ol-fluoroquench","ol-bulk-monoclonal"],
  },
  "Instruments & Software": {
    "Readers & Analysers": ["ol-labscan3d","ol-labscan100"],
    "Software": ["ol-typestream","ol-fusion"],
    "Automated Pipettor": ["ol-hla-pro"],
  },
  "Post-Transplant Monitoring": {
    "Chimerism Monitoring": ["ol-chimerism-ngs","ol-chimerism"],
    "Donor-Derived Cell-Free DNA": ["ol-accept-cfdna"],
  },
};

export const products: Product[] = [
  // ═══ ONE LAMBDA — ANTIBODY DETECTION ═══════════════════════════════════════

  { id:"ol-labscreen-sa1", name:"LABScreen™ Single Antigen HLA Class I", brand:"onelambda", category:"transplant", subcategory:"Luminex-based HLA Antibody Identification",
    image:"/images/ol-labscreen-sa1.jpg",
    description:"Single antigen assays provide a unique solution to the dilemma presented by high PRA patients. In these patients, antibody reactive to one or more dominant epitopes can mask the presence of additional antibody specificities. These specificities can now be identified by single antigen technology.", featured:true,
    tags:["hla","transplant","antibody","class-i","luminex"],
    highlights:[
      "Unique solution for high-PRA patients where dominant epitopes mask additional specificities",
      "Single antigen technology identifies all antibody specificities",
      "HLA Class I (A, B, C) — over 90 specificities per kit",
      "FDA 510(k) cleared, CE-IVD marked",
    ],
    features:["Single purified recombinant HLA Class I antigen per bead","PE-conjugated anti-human IgG fluorescent detection","High inter-assay reproducibility","HLA Fusion™ software compatible","Interpretable with automated cut-off application"],
    applications:["Pre-transplant HLA antibody identification","Unacceptable antigen determination for transplant listing","Virtual crossmatch — Class I","Post-transplant donor-specific antibody (DSA) monitoring","Panel Reactive Antibody (PRA) assessment"],
    specs:{"HLA Loci":"HLA-A, B, C (Class I)","Specificities":"> 90","Detection Method":"PE anti-human IgG","Sample Type":"Human serum","Sample Volume":"20 µL per reaction","Incubation Time":"30 minutes","Regulatory Status":"FDA 510(k) cleared, CE marked"},
    packaging:[
      {name:"LABScreen™ Single Antigen Class I",catalogueNumber:"LS1A04",units:"1 Kit",format:"96-well microplate"},
      {name:"LABScreen™ Single Antigen Class I HD",catalogueNumber:"LS1A04HD",units:"1 Kit",format:"96-well microplate, High Definition"},
    ],
    relatedProducts:["ol-labscreen-sa2","ol-labscreen-mixed","ol-labscan3d","ol-c1qscreen"] },

  { id:"ol-labscreen-sa2", name:"LABScreen™ Single Antigen HLA Class II", brand:"onelambda", category:"transplant", subcategory:"Luminex-based HLA Antibody Identification",
    image:"/images/ol-labscreen-sa2.jpg",
    description:"Single antigen assays provide a unique solution to the dilemma presented by high PRA patients. In these patients, antibody reactive to one or more dominant epitopes can mask the presence of additional antibody specificities. These specificities can now be identified by single antigen technology.", featured:true,
    tags:["hla","transplant","antibody","class-ii","luminex"],
    highlights:[
      "Unique solution for high-PRA patients where dominant epitopes mask additional specificities",
      "Single antigen technology identifies all HLA Class II antibody specificities",
      "Covers DRB1, DRB3/4/5, DQA1, DQB1, DPA1, DPB1 loci",
      "FDA 510(k) cleared, CE-IVD marked",
    ],
    features:["Single purified recombinant HLA Class II antigen per bead","Alpha-beta heterodimer pairs for DQ and DP","PE-conjugated anti-human IgG detection","HLA Fusion™ software compatible"],
    applications:["Pre-transplant HLA Class II antibody identification","DQ and DP antibody specificity determination","Virtual crossmatch — Class II","Post-transplant DSA monitoring"],
    specs:{"HLA Loci":"DRB1, DRB3/4/5, DQA1, DQB1, DPA1, DPB1","Specificities":"> 100","Detection Method":"PE anti-human IgG","Sample Volume":"20 µL per reaction","Regulatory Status":"FDA 510(k) cleared, CE marked"},
    packaging:[
      {name:"LABScreen™ Single Antigen Class II",catalogueNumber:"LS2A04",units:"1 Kit",format:"96-well microplate"},
      {name:"LABScreen™ Single Antigen Class II HD",catalogueNumber:"LS2A04HD",units:"1 Kit",format:"96-well microplate, High Definition"},
    ],
    relatedProducts:["ol-labscreen-sa1","ol-labscreen-mixed","ol-labscan3d","ol-c1qscreen"] },

  { id:"ol-labscreen-mixed", name:"LABScreen™ Mixed Class I & II Antibody Screening", brand:"onelambda", category:"transplant", subcategory:"Luminex-based HLA Antibody Identification",
    image:"/images/ol-labscreen-mixed.jpg",
    highlights:[
      "Tests for HLA Class I, Class II and MICA antibodies in a single tube protocol",
      "Well suited for monthly patient antibody screens",
      "Works in both low and high throughput laboratories",
      "Fast first-line screening before single antigen testing",
    ],
    description:"LABScreen Mixed Tests for the presence of HLA Class I and Class II antibodies, as well as MICA antibodies, with a single tube protocol. Well suited for monthly patient antibody screens in both low and high throughput laboratories.",
    tags:["hla","transplant","screening"],
    packaging:[{name:"LABScreen™ Mixed",catalogueNumber:"LSMA04",units:"1 Kit",format:"96-well microplate"}],
    relatedProducts:["ol-labscreen-sa1","ol-labscreen-sa2"],
    features:["Simultaneous Class I and Class II antibody detection in one well","Mixed bead cocktail covering HLA-A, B, C, DR, DQ, DP antigens","PE-conjugated anti-human IgG fluorescent detection","Semi-quantitative MFI results","Compatible with LABScan3D™ and FLEXMAP 3D®"],
    applications:["Initial HLA antibody screening for all transplant candidates","Pre-transplant sensitisation assessment","Triage of samples for single-antigen testing","Post-transfusion sensitisation monitoring","Periodic re-screening of wait-listed patients"],
    specs:{"Coverage":"Class I (HLA-A,B,C) + Class II (DR,DQ,DP)","Assay Time":"~60 minutes","Sample Volume":"20 µL","Format":"96-well microplate","Regulatory":"FDA cleared, CE marked"},
   },

  { id:"ol-labscreen-pra", name:"LABScreen™ PRA", brand:"onelambda", category:"transplant", subcategory:"Luminex-based HLA Antibody Identification",
    image:"/images/ol-labscreen-pra.jpg",
    highlights:[
      "Determines percent PRA and identifies antibody specificities",
      "HLA antigens purified from different cells for broad coverage",
      "HLA Class I and Class II PRA tests may be used separately or together",
      "Automated PRA calculation with HLA Fusion™ software",
    ],
    description:"Determines percent PRA and identifies antibody specificities using HLA antigens purified from different cells. HLA Class I and Class II PRA tests may be used separately or together.",
    tags:["hla","transplant","pra","screening"],
    packaging:[
      {name:"LABScreen™ PRA Class I",catalogueNumber:"LSPRA1A04",units:"1 Kit",format:"96-well microplate"},
      {name:"LABScreen™ PRA Class II",catalogueNumber:"LSPRA2A04",units:"1 Kit",format:"96-well microplate"},
    ],
    features:["Calculates percentage Panel Reactive Antibody (PRA)","Separate Class I and Class II PRA values","Luminex xMAP® bead-based assay","Automated PRA calculation with HLA Fusion™","Suitable for high-throughput screening"],
    applications:["Pre-transplant sensitisation level assessment","Wait-list PRA monitoring for organ allocation","Post-sensitisation event assessment (transfusion, pregnancy)","Determining need for single-antigen testing"],
    specs:{"PRA Output":"Class I % PRA, Class II % PRA","Format":"96-well microplate","Analyzer":"LABScan3D™, FLEXMAP 3D®","Sample Volume":"20 µL","Regulatory":"FDA cleared, CE marked"},
   },

  { id:"ol-labscreen-mica", name:"LABScreen™ MICA Single Antigen Group 1", brand:"onelambda", category:"transplant", subcategory:"Luminex-based HLA Antibody Identification",
    image:"/images/ol-labscreen-mica.jpg",
    highlights:[
      "Single antigen panel specifically designed to identify MICA antibodies",
      "Luminex xMAP® bead technology for precise MICA specificity identification",
      "Important for comprehensive non-HLA antibody assessment",
    ],
    description:"LABScreen Single Antigen MICA A single antigen panel designed to identify MICA antibodies.",
    tags:["mica","non-hla","transplant"],
    packaging:[{name:"LABScreen™ MICA Single Antigen Group 1",catalogueNumber:"LSM12A04",units:"1 Kit",format:"96-well microplate"}],
    features:["Single MICA antigen per bead for precise specificity identification","Detects IgG antibodies against MICA alleles","Luminex xMAP® platform","Compatible with LABScan3D™"],
    applications:["Non-HLA antibody identification for transplant risk assessment","MICA antibody monitoring post-transplant","Research into MICA antibody-mediated rejection"],
    specs:{"Target":"MICA antigens","Method":"Luminex single-antigen beads","Format":"96-well microplate","Regulatory":"CE marked, RUO in some regions"},
   },

  { id:"ol-labscreen-explex", name:"LABScreen™ Single Antigen ExPlex Assay", brand:"onelambda", category:"transplant", subcategory:"Luminex-based HLA Antibody Identification",
    image:"/images/ol-labscreen-explex.jpeg",
    highlights:[
      "Best-in-class coverage: 151 Class I or 119 Class II CWD alleles in a single well",
      "Enhanced coverage to better correlate with molecular typing",
      "Provides broader antibody reactivity data to evaluate eplet patterns",
      "Identifies antibodies against rare specificities missed by standard SAB panels",
    ],
    description:"Best-in-class coverage • Total of 151 Class I or 119 Class II common and well-documented (CWD) alleles in a single well • Enhanced coverage to better correlate with molecular typing • Provides broader antibody reactivity data to evaluate eplet patterns",
    tags:["hla","transplant","antibody"],
    packaging:[
      {name:"LABScreen™ SA ExPlex Class I",catalogueNumber:"LSA1EPXA04",units:"1 Kit",format:"96-well microplate"},
      {name:"LABScreen™ SA ExPlex Class II",catalogueNumber:"LSA2EPXA04",units:"1 Kit",format:"96-well microplate"},
    ],
    features:[
      "Total of 151 Class I or 119 Class II common and well-documented (CWD) alleles per well",
      "Enhanced correlation with molecular typing results",
      "Broader antibody reactivity data for eplet pattern evaluation",
      "Single-well format for Class I and Class II extended panels",
      "Compatible with LABScan3D™ and FLEXMAP 3D® analyzers",
    ],
    applications:["Complex sensitised patients with broad antibody profiles","Identification of rare HLA antibody specificities","Confirmation of antibody patterns from standard SAB testing"],
    specs:{"Coverage":"Extended Class I and Class II specificities","Format":"96-well microplate","Analyzer":"LABScan3D™, FLEXMAP 3D®","Regulatory":"CE marked"},
   },

  { id:"ol-labscreen-ancillary", name:"LABScreen™ Ancillary Reagents", brand:"onelambda", category:"transplant", subcategory:"Luminex-based HLA Antibody Identification",
    image:"/images/ol-labscreen-ancillary.jpg",
    highlights:[
      "Negative control serum indicates non-specific background signal",
      "Validates assay performance for LABScreen™ and LABScreen Multi beads",
      "Confirms absence of anti-HLA Class I or Class II antibody",
      "Essential for laboratory accreditation and QC compliance",
    ],
    description:"Negative control serum used as an indicator of the non-specific background signal of each LABScreen and LABScreen Multi bead when reacting with a serum sample that does not contain any anti-HLA Class I or Class II antibody.",
    tags:["ancillary","reagents","labscreen"],
    packaging:[
      {name:"LABScreen™ Control Sera",catalogueNumber:"LSCONTXA",units:"1 Kit",format:"Control sera"},
      {name:"LABScreen™ Wash Buffer",catalogueNumber:"LSWASH0X",units:"1 Bottle",format:"Concentrate"},
    ],
    features:["Wash buffer optimised for LABScreen™ assays","Control sera for positive and negative QC","Serum diluent for sample normalisation","Pre-validated reagents for LABScreen™ workflows"],
    applications:["Quality control in LABScreen™ SAB and Mixed assays","Standardisation of laboratory workflows","Compliance with laboratory accreditation requirements"],
    specs:{"Components":"Wash buffer, control sera, diluent","Compatibility":"All LABScreen™ assay kits","Storage":"2–8 °C"},
   },

  { id:"ol-c1qscreen", name:"C1qScreen™ HLA Antibody Detection", brand:"onelambda", category:"transplant", subcategory:"Complement Binding HLA Antibody Identification",
    image:"/images/ol-c1qscreen.webp",
    description:"Regulatory: CE-IVD: For In Vitro Diagnostic Use. (European Union Only) Technique: Flow Analysis Use: For the detection of complement-binding HLA antibodies in human serum. Storage Temperature: -65° C or below Package Includes: C1q protein, PE-labeled anti-C1q, C1q positive control beads, HEPES Buffer (10X)", featured:true,
    tags:["complement","c1q","amr","transplant","dsa"],
    highlights:[
      "Detects complement-binding HLA antibodies in human serum",
      "CE-IVD: For In Vitro Diagnostic Use (European Union)",
      "Includes C1q protein, PE-labeled anti-C1q, and positive control beads",
      "Storage: -65°C or below",
    ],
    specs:{
      "Regulatory":"CE-IVD (European Union)",
      "Technique":"Flow Analysis (Luminex xMAP®)",
      "Use":"Detection of complement-binding HLA antibodies in human serum",
      "Storage Temperature":"-65°C or below",
      "Kit Includes":"C1q protein, PE-labeled anti-C1q, C1q positive control beads, HEPES Buffer (10X)",
    },
    packaging:[
      {name:"C1qScreen™ Class I",catalogueNumber:"C1QSA1HD04",units:"1 Kit",format:"96-well microplate"},
      {name:"C1qScreen™ Class II",catalogueNumber:"C1QSA2HD04",units:"1 Kit",format:"96-well microplate"},
    ],
    relatedProducts:["ol-labscreen-sa1","ol-labscreen-sa2"],
    features:[
      "Flow analysis technique using Luminex xMAP® bead platform",
      "Detects HLA antibodies that fix complement component C1q",
      "Kit includes: C1q protein, PE-labeled anti-C1q, C1q positive control beads, HEPES Buffer (10X)",
      "Distinguishes clinically relevant complement-activating DSA from non-fixing antibodies",
      "Key predictor of antibody-mediated rejection (AMR) risk",
    ],
    applications:["Risk stratification of donor-specific antibodies (DSA)","Pre-transplant donor selection for sensitised patients","Post-transplant AMR diagnosis and monitoring","Clinical research on complement-activating HLA antibodies"],
   },

  { id:"ol-flowdsa-xm", name:"FlowDSA-XM™ Advanced Crossmatch", brand:"onelambda", category:"transplant", subcategory:"Advanced Crossmatch Testing",
    image:"/images/ol-flowdsa-xm.jpeg",
    highlights:[
      "Selectively distinguishes leukocyte antibodies from autoantibodies",
      "Combines traditional flow cytometry crossmatch with microbead technology specificity",
      "Selective detection of donor-specific antibodies in the first run",
      "Advances the science of crossmatch testing beyond CDC methodology",
    ],
    description:"Distinguish leukocyte antibodies from autoantibodies Our FlowDSA-XM assay is a flow cytometry-based crossmatch assay optimized for the detection of leukocyte antibodies. Combining traditional flow cytometry cellular crossmatch testing with the specificity of microbeads technology, the FlowDSA-XM test selectively distinguishes leukocyte antibodies, allowing you to obtain selective detection in the first run. FlowDSA-XM advances the science of crossmatch testing by combining traditional flow cytometry with microbead technology. Together, these proven technologies selectively distinguish human leukocyte antigen antibodies from autoantibodies, allowing you to obtain selective detection in the first run. FlowDSA-XM assay features Crossmatch testing that distinguishes leukocyte antibodies from autoantibodies Compatible with most standard single-laser flow cytometers Works with lymphocytes from fresh or frozen sources (peripheral blood, lymph nodes, or spleen) Familiar workflow",
    tags:["crossmatch","dsa","flow-cytometry","transplant"],
    packaging:[{name:"FlowDSA-XM™",catalogueNumber:"FLOWDSA",units:"1 Kit",format:"Flow cytometry"}],
    features:[
      "Flow cytometry-based crossmatch assay optimised for leukocyte antibody detection",
      "Combines cellular crossmatch with xMAP® microbead specificity",
      "Selectively distinguishes leukocyte antibodies from autoantibodies",
      "Selective detection achievable in the first run — no repeat testing required",
      "Greater sensitivity than complement-dependent cytotoxicity (CDC) crossmatch",
    ],
    applications:["Virtual and physical crossmatch for transplant donors","Detection of low-level DSA missed by CDC","Pre-transplant DSA risk assessment","Post-transplant monitoring for de novo DSA"],
    specs:{"Method":"Flow cytometry crossmatch","Sensitivity":"Superior to CDC crossmatch","HLA Coverage":"Class I and Class II","Equipment":"Standard flow cytometer","Regulatory":"CE marked"},
   },

  { id:"ol-magsort", name:"One Lambda™ MagSort™", brand:"onelambda", category:"transplant", subcategory:"Advanced Antibody Testing",
    image:"/images/ol-magsort.jpeg",
    highlights:[
      "Targeted isolation of HLA antibodies using single HLA-antigen coated magnetic beads",
      "Covers 6 classical loci: HLA-A, B, C, DR, DQ, DP",
      "Enables focused antibody assessment without cross-reactivity",
      "Adsorption/elution technology for precise antibody isolation",
    ],
    description:"Targeted isolation of HLA antibodies from human sera using adsorption/elution via HLA-specific antigen-coated magnetic beads HLA-antibody isolation One Lambda™ MagSort™ comprises of a comprehensive panel of single HLA-antigen bound magnetic beads covering 6 classical loci – HLA-A, B, C, DR, DQ and DP. The technology enables elution of targeted HLA antibodies from complex serum, thereby facilitating focused antibody assessment without the extent of cross-reactivity which may occur in the primary serum. One Lambda™ MagSort™ can be applied to: Isolation of individual HLA antibodies of interest (e.g. donor specific antibody) to explore antibody properties, including through downstream cellular (e.g. flow cytometric crossmatch) and solid-phase assays (e.g. LABScreen Single Antigen & Single Antigen ExPlex). Enhancing eplet-level HLA-antibody specificity analysis, supported by HLA Matchmaker functionality within HLA Fusion software. Includes potential for novel eplet discovery based on unique antibody binding patterns. Assessment of HLA eplet immunogenicity. Distinguishing genuine reactivity from background reactivity and aiding in identification of weak reactivity. Determining polyclonal or monoclonal nature of HLA-antibody profile. In specific cases, indirect assessment of relative HLA-antibody quantity and binding strength.",
    tags:["antibody","magsort","prozone"],
    packaging:[{name:"MagSort™ Class I & II",catalogueNumber:"MAGSORT04",units:"1 Kit",format:"Magnetic beads"}],
    features:[
      "Comprehensive panel of single HLA-antigen bound magnetic beads",
      "Covers 6 classical HLA loci: A, B, C, DR, DQ, and DP",
      "Adsorption and elution of targeted HLA antibodies from complex serum",
      "Facilitates focused antibody assessment without cross-reactivity",
      "Resolves prozone/hook effect that can mask true antibody levels",
      "Works with standard magnetic separators",
    ],
    applications:["Elimination of prozone effect in high-PRA patients","Removal of interfering substances from patient sera","Pre-treatment of samples before SAB antibody testing"],
    specs:{"Method":"Magnetic bead separation","Compatible Assays":"LABScreen™ Single Antigen Class I and II","Sample Treatment":"Pre-incubation step","Regulatory":"RUO"},
   },

  { id:"ol-alltype-ngs", name:"AllType™ NGS HLA Typing Kit", brand:"onelambda", category:"ngs", subcategory:"Next-Generation Sequencing",
    image:"/images/ol-alltype-ngs.jpeg",
    description:"Next-Generation Sequencing (NGS) technology has revolutionized the field of Human Leukocyte Antigen (HLA) typing, which is critical for organ transplantation, disease association studies, and immune response research. NGS offers a powerful, precise, and efficient approach for high resolution HLA typing, improving the matching process in transplantation and enhancing our understanding of the genetic foundations of the immune system. Many labs might find NGS difficult to adopt due to the increased complexity, dedicated labor requirements and data management challenges. Laboratory throughput influences the strategy used in consolidating genotyping technologies. We offer a comprehensive portfolio that meets the diverse needs of the HLA genotyping market and our One Lambda NGS assays are designed for simplicity and flexibility allowing laboratories greater cross-training on their platform of choice.", featured:true,
    tags:["hla","typing","ngs","allele-level"],
    highlights:[
      "Revolutionises HLA typing with Next-Generation Sequencing precision",
      "High-resolution typing improving transplant matching outcomes",
      "Designed for labs adopting NGS — minimal learning curve",
      "Critical for organ transplantation, disease association and immune research",
    ],
    features:[
      "NGS-based high-resolution HLA typing across 11 loci in one run",
      "Allele-level, phased genotyping from a single amplification",
      "Improves transplant matching through higher typing resolution",
      "Compatible with Illumina® MiSeq and Ion Torrent™ platforms",
      "TypeStream™ Visual software for automated analysis and reporting",
      "CE-IVD marked for transplant diagnostic use",
    ],
    applications:["Donor and recipient HLA typing for transplantation","Bone marrow / stem cell donor registry typing","High-resolution research typing","Novel allele discovery"],
    specs:{"Loci":"HLA-A,B,C,DRB1,DRB3/4/5,DQA1,DQB1,DPA1,DPB1","Resolution":"Allele-level (4-field, phased)","DNA Input":"50 ng","Platforms":"Illumina® MiSeq, Ion Torrent™","Turnaround":"< 24 hours","Software":"TypeStream™ Visual","Regulatory":"CE-IVD marked"},
    packaging:[
      {name:"AllType™ NGS 8-Sample Kit",catalogueNumber:"OLI8A",units:"8 Samples",format:"NGS amplification kit"},
      {name:"AllType™ NGS 24-Sample Kit",catalogueNumber:"OLI24A",units:"24 Samples",format:"NGS amplification kit"},
      {name:"AllType™ NGS 96-Sample Kit",catalogueNumber:"OLI96A",units:"96 Samples",format:"NGS amplification kit"},
    ],
    relatedProducts:["ol-alltype-fastplex","ol-typestream","ol-labscan3d"] },

  { id:"ol-alltype-fastplex", name:"AllType™ FASTplex™ NGS", brand:"onelambda", category:"ngs", subcategory:"Next-Generation Sequencing",
    image:"/images/ol-alltype-fastplex.jpeg",
    highlights:[
      "Sample to sequencing in less than 7 hours — completed in a single day",
      "Less than 90 minutes hands-on time",
      "Reportable results in 1.5 days or less",
      "CE-IVD compliant with minimal learning curve",
    ],
    description:"AllType™ FASTplex™ NGS provides a fast, CE-IVD compliant method for HLA NGS. Sample to sequencing in less than 7 hours ensures the AllType™ FASTplex™ workflow is completed in a single-day (with less than 90 minutes hands-on time), with reportable results 1.5 days or less. The simple method requires a minimal learning curve. The AllType™ FASTplex™ NGS assay is a rapid, high-resolution HLA typing solution from One Lambda (Thermo Fisher Scientific) designed for transplant diagnostics. It offers a single-day protocol (< 7 hours total, < 90 min hands-on) by utilizing a single-tube, 11-loci multiplex PCR workflow that covers HLA Class I and Class II, providing efficient, cost-effective, and accurate genotyping with minimal pipetting. High-resolution genotyping: intelligently simple Key Features and Benefits: Amplification: One PCR reaction per sample Multiplexed amplification of all HLA Class I and Class II loci in 2.5 hours: HLA-A, B, C, DRB1, DRB3/4/5, DQA1, DQB1, DPA1 and DPB1 Enhanced gene coverage No pooling of amplicons Library preparation: Early sample pooling Single-tube protocols for library processing Low number of pipetting events Compatible with Illumina™ MiSeq™, MiniSeq™ and iSeq™, and Ion GeneStudio™ S5 Systems",
    tags:["hla","ngs","typing","fast"],
    packaging:[
      {name:"AllType™ FASTplex™ 24-Sample",catalogueNumber:"OLIFPX24A",units:"24 Samples",format:"NGS amplification kit"},
      {name:"AllType™ FASTplex™ 96-Sample",catalogueNumber:"OLIFPX96A",units:"96 Samples",format:"NGS amplification kit"},
    ],
    relatedProducts:["ol-alltype-ngs","ol-typestream"],
    features:[
      "Fast, CE-IVD compliant method for HLA NGS",
      "Complete workflow in a single day (< 7 hours sample to sequencing)",
      "Less than 90 minutes hands-on time",
      "Reportable results in 1.5 days or less",
      "Simple method requiring minimal learning curve",
      "Processes single or multiple samples on Illumina platforms",
    ],
    applications:["High-throughput clinical HLA typing labs","Rapid donor typing for time-critical transplants","Registry typing with accelerated turnaround"],
    specs:{"Loci":"HLA-A,B,C,DRB1,DRB3/4/5,DQA1,DQB1,DPA1,DPB1","Resolution":"Allele-level","Platform":"Illumina short-read","Software":"TypeStream™ Visual","Regulatory":"CE marked"},
   },

  { id:"ol-alltype-rapid", name:"AllType™ Rapid 11 Loci Kit", brand:"onelambda", category:"ngs", subcategory:"Next-Generation Sequencing",
    image:"/images/ol-alltype-rapid.jpeg",
    highlights:[
      "Single sample results in under 4.5 hours",
      "Multi-sample results in under 11 hours",
      "Compatible with Oxford Nanopore Technologies (MinION Mk1, 4 Flow Cell)",
      "Completely phased long-range sequencing — ligase-based library prep",
    ],
    description:"High-resolution genotyping: high quality results with less complexity Key Features and Benefits: Flexible and Rapid Workflow: Single and multi-sample workflows (up to 24 samples) Single sample results in <4.5 hours Multi-sample results in <11 hours Compatible with Oxford Nanopore Technologies 4 Flow cell MinION Mk1 Sequencing Devices Phased Genotyping: Ligase-based library preparation (no fragmentation) Completely phased long-range sequencing Helps resolve relevant second-field phase (cis-trans) ambiguities Quality Performance: >99% second-field concordance Highly uniform coverage Balanced reads",
    tags:["hla","ngs","rapid","typing"],
    packaging:[{name:"AllType™ Rapid 11 Loci",catalogueNumber:"OLIRAP24A",units:"24 Samples",format:"NGS amplification kit"}],
    features:[
      "Flexible single and multi-sample workflows (up to 24 samples)",
      "Single sample results in < 4.5 hours",
      "Multi-sample results in < 11 hours",
      "Compatible with Oxford Nanopore Technologies (4 Flow Cell, MinION Mk1)",
      "Ligase-based library preparation — no fragmentation required",
      "Completely phased long-range sequencing",
      "Resolves second-field phase (cis-trans) ambiguities",
    ],
    applications:["Emergency and urgent transplant donor typing","Rapid allele-level typing for living donors","Time-critical registry searches"],
    specs:{"Loci":"11 HLA loci","Resolution":"Allele-level","Platform":"Illumina","Software":"TypeStream™ Visual","Regulatory":"CE marked"},
   },

  { id:"ol-hybritype", name:"One Lambda™ HybriType™ NGS Hybrid Capture Assay", brand:"onelambda", category:"ngs", subcategory:"Next-Generation Sequencing",
    image:"/images/ol-hybritype.png",
    highlights:[
      "Probe-based design optimises read balance and uniformity",
      "Mitigates allele dropout for accurate, quality results",
      "Complete workflow in less than 5.5 hours, under 2.5 hours hands-on",
      "Automated analysis via TypeStream™ Visual with gene copy number detection",
    ],
    description:"The One Lambda™ HybriType™ NGS Hybrid Capture Assay utilises a probe-based design to optimise read balance and uniformity; potentially mitigating allele dropout for accurate, quality results. The streamlined workflow takes less than 5.5 hours with under 2.5 hands-on time. Sequencing data are analysed using TypeStream™ Visual NGS Analysis Software enabling rapid automated analysis and gene copy number detection. Reporting and advanced analytics are facilitated by integration within the One Lambda software ecosystem (HLA Fusion™ analysis software and HistoTrac laboratory management system).",
    tags:["hla","ngs","hybrid-capture","abo","mica"],
    packaging:[{name:"HybriType™ HLA Plus ABO Flex Kit 96",catalogueNumber:"03HYB18ABOFX",units:"96 Samples",format:"Hybrid capture NGS kit"}],
    relatedProducts:["ol-alltype-ngs","ol-typestream"],
    features:[
      "Probe-based hybrid capture design for optimised read balance and uniformity",
      "Mitigates allele dropout for accurate and high-quality results",
      "Streamlined workflow: < 5.5 hours total, < 2.5 hours hands-on",
      "Covers classical HLA, non-classical HLA, MICA/MICB, and ABO blood groups",
      "Automated analysis and gene copy number detection via TypeStream™ Visual",
      "Integration within One Lambda HLA Fusion™ software for reporting and analytics",
    ],
    applications:["Comprehensive HLA and ABO typing in single workflow","Research into non-classical HLA and MICA gene variation","High-resolution typing including introns and UTRs","Donor registry full-gene typing"],
    specs:{"Method":"Probe-based NGS hybrid capture","Loci":"Classical HLA + non-classical + MICA/MICB + ABO","Platform":"Illumina","Turnaround":"< 5.5 hours","Samples/Run":"96","Software":"TypeStream™ Visual","Regulatory":"CE marked"},
   },

  { id:"ol-microssp-generic", name:"Micro SSP™ Generic HLA Typing Trays", brand:"onelambda", category:"molecular", subcategory:"Sequence-Specific Primer Typing",
    image:"/images/ol-microssp-generic.jpg",
    highlights:[
      "Assigns HLA Class I or Class II alleles individually or simultaneously",
      "96-well format with pre-aliquoted and dispensed primers",
      "Internal control in each well",
      "Fast result within 2 hours",
    ],
    description:"One Lambda’s Micro SSP™ Generic trays are available to assign HLA Class I or Class II alleles individually or simultaneously; 96-well format (unless otherwise stated) with pre-aliquoted and dispensed primers and an internal control in each well providing a fast result within 2 hours.", featured:true,
    tags:["hla","ssp","typing","class-i","class-ii"],
    packaging:[
      {name:"Micro SSP™ Generic Class I Tray",catalogueNumber:"MSSPA004",units:"10 Trays",format:"96-well SSP tray"},
      {name:"Micro SSP™ Generic Class II Tray",catalogueNumber:"MSSPA2004",units:"10 Trays",format:"96-well SSP tray"},
    ],
    relatedProducts:["ol-microssp-highres","ol-alltype-ngs"],
    features:[
      "Available for HLA Class I or Class II allele assignment — individually or simultaneously",
      "96-well format (unless otherwise stated) for high-throughput processing",
      "Pre-aliquoted and dispensed primers — ready to use",
      "Internal control in each well for quality assurance",
      "Results within 2 hours using a standard thermocycler",
      "Room-temperature lyophilised storage for convenience",
    ],
    applications:["Routine transplant donor and recipient HLA typing","Low-to-intermediate resolution clinical typing","Confirmatory typing following serological or SSO screening","Laboratories without NGS capability"],
    specs:{"Method":"Sequence-Specific Primer (SSP) PCR","Resolution":"Low to intermediate","Equipment":"Standard thermocycler + gel electrophoresis","Result Time":"< 3 hours","Storage":"Room temperature (lyophilised)","Software":"UniMatch™"},
   },

  { id:"ol-labtype-sso", name:"LABType™ SSO HLA Typing", brand:"onelambda", category:"molecular", subcategory:"Reverse SSO Typing",
    image:"/images/ol-labtype-sso.jpg",
    description:"LABType™ SSO (Sequence-Specific Oligonucleotide) HLA typing kits, developed by One Lambda (Thermo Fisher Scientific), are advanced molecular assays for identifying HLA alleles. They combine PCR amplification with Luminex bead technology for rapid, scalable, and accurate intermediate-to-high resolution typing of HLA Class I and Class II loci, commonly used in transplantation and disease association studies Key Features and BenefitsMethodology: Uses reverse-SSO (rSSO) technology, where PCR products are hybridized to oligonucleotide probes immobilized on fluorescent microspheres.Technology Platform: Analyzed using Luminex flow analyzers (LABScan™ 100 or LABScan3D™).Efficiency: Streamlined, single-well workflow reduces labor, reagent usage, and turnaround time compared to traditional membrane-based methods.Accuracy: Delivers accurate 2-digit (low) to 4-digit (intermediate/high) resolution for HLA A, B, C, DRB1/3/4/5, DQA1/DQB1, and DPA1/DPB1", featured:true,
    tags:["hla","sso","typing","luminex"],
    highlights:[
      "Reverse-SSO (rSSO) technology using Luminex xMAP® bead arrays",
      "Rapid, scalable, and accurate intermediate-to-high resolution typing",
      "Compatible with LABScan3D™ and LABScan™ 100 analyzers",
      "Used in transplantation and disease association studies",
    ],
    features:[
      "Reverse-SSO (rSSO): PCR products hybridise to bead-bound SSO probes",
      "Luminex xMAP® bead technology for high-throughput multiplexed typing",
      "Intermediate-to-high resolution HLA Class I and Class II typing",
      "Automated analysis with HLA Fusion™ software",
      "Compatible with LABScan3D™ and LABScan™ 100 analyzers",
      "Scalable from small to large sample batches",
    ],
    applications:[
      "Donor and recipient HLA typing for solid organ transplantation",
      "Haematopoietic stem cell donor typing",
      "Intermediate-resolution HLA typing for clinical labs",
      "Complement to NGS or SBT for confirmation typing",
    ],
    specs:{"Method":"Reverse SSO (rSSO) on Luminex xMAP® beads","Resolution":"Intermediate to high","Analyzer":"LABScan3D™, LABScan™ 100","Turnaround":"6 hours","Format":"96-well microplate","Software":"HLA Fusion™","Regulatory":"CE marked"},
    packaging:[
      {name:"LABType™ SSO HLA-A",catalogueNumber:"LABTYPA04",units:"1 Kit",format:"96-well microplate"},
      {name:"LABType™ SSO HLA-B",catalogueNumber:"LABTYPB04",units:"1 Kit",format:"96-well microplate"},
      {name:"LABType™ SSO HLA-C",catalogueNumber:"LABTYPCC04",units:"1 Kit",format:"96-well microplate"},
      {name:"LABType™ SSO HLA-DRB1",catalogueNumber:"LABTYPDRB04",units:"1 Kit",format:"96-well microplate"},
      {name:"LABType™ SSO HLA-DQB1",catalogueNumber:"LABTYPD04",units:"1 Kit",format:"96-well microplate"},
    ],
    relatedProducts:["ol-labtype-ancillary","ol-labscan3d","ol-alltype-ngs"] },

  { id:"ol-labtype-ancillary", name:"LABType™ Ancillary Reagents", brand:"onelambda", category:"molecular", subcategory:"Reverse SSO Typing",
    image:"/images/ol-labtype-ancillary.jpeg",
    highlights:[
      "Essential buffers and components for LABType rSSO HLA typing assays",
      "Includes Taq polymerase, buffers, and primer mixes",
      "Ensures optimal, high-resolution DNA amplification performance",
      "Available in 20 or 100-test packages",
    ],
    description:"LABType™ Ancillary Reagents are essential buffers and components designed by One Lambda to support LABType rSSO HLA typing assays. These products, including Taq polymerase, buffers, and primer mixes, ensure optimal, high-resolution performance for DNA amplification and HLA typing, often sold in 20 or 100-test packages",
    tags:["ancillary","labtype","sso"],
    packaging:[{name:"LABType™ Ancillary Kit",catalogueNumber:"LABTYP-ANC",units:"1 Kit",format:"Ancillary reagents"}],
    features:[
      "Includes Taq polymerase, assay buffers, and primer mixes",
      "Designed specifically for LABType™ rSSO HLA typing workflows",
      "Ensures optimal and consistent DNA amplification performance",
      "Pre-validated components for high-resolution HLA typing",
      "Available in 20-test and 100-test package sizes",
    ],
    applications:["Essential workflow reagents for LABType™ SSO typing","Standardising rSSO protocol across runs","Quality-controlled components for laboratory accreditation"],
    specs:{"Components":"Denaturation reagent, hybridisation buffer, wash buffer","Compatibility":"LABType™ SSO all loci kits","Storage":"2–8 °C"},
   },

  { id:"ol-secore-sbt", name:"SeCore™ SBT HLA Typing Kits", brand:"onelambda", category:"molecular", subcategory:"Sequence Based Typing",
    image:"/images/ol-secore-sbt.jpeg",
    highlights:[
      "High-resolution, Sanger sequencing-based HLA typing",
      "Unambiguous, locus-specific identification of Class I and II HLA",
      "Rapid 1.5-hour amplification",
      "Integrated ExoSAP-IT™ cleanup and uTYPE® Dx Software analysis",
    ],
    description:"SeCore™ SBT HLA Typing Kits are high-resolution, Sanger sequencing-based solutions by Thermo Fisher Scientific designed to provide unambiguous, locus-specific identification of Class I and II Human Leukocyte Antigens (HLA). They offer a rapid, 1.5-hour amplification, with integrated workflows that include ExoSAP-IT™ for cleanup and uTYPE® Dx Software for analysis.",
    tags:["hla","sbt","typing","sanger"],
    packaging:[
      {name:"SeCore™ SBT HLA-A",catalogueNumber:"SECSBT-A",units:"1 Kit",format:"SBT amplification kit"},
      {name:"SeCore™ SBT HLA-B",catalogueNumber:"SECSBT-B",units:"1 Kit",format:"SBT amplification kit"},
      {name:"SeCore™ SBT HLA-DRB1",catalogueNumber:"SECSBT-DRB",units:"1 Kit",format:"SBT amplification kit"},
    ],
    features:[
      "Sanger sequencing-based high-resolution HLA genotyping",
      "Unambiguous locus-specific identification of HLA Class I and Class II",
      "Rapid 1.5-hour PCR amplification step",
      "Integrated ExoSAP-IT™ cleanup for streamlined workflow",
      "uTYPE® Dx Software for automated allele assignment and reporting",
      "Gold standard method for unambiguous allele determination",
    ],
    applications:["High-resolution allele-level HLA typing","Unambiguous allele assignment for complex cases","Confirmatory typing in transplant and registry programmes","Novel allele sequencing and characterisation"],
    specs:{"Method":"Sequence-Based Typing (SBT) — Sanger sequencing","Resolution":"Allele-level","Sequencing":"Standard capillary electrophoresis (Sanger)","Software":"SeqA™","Regulatory":"CE marked"},
   },

  { id:"ol-linkseq-hla-kir", name:"LinkSēq™ HLA and KIR Typing Kits", brand:"onelambda", category:"molecular", subcategory:"LinkSeq Real-Time PCR",
    image:"/images/ol-linkseq-hla-kir.jpeg",
    highlights:[
      "Results in under 90 minutes with only 10 minutes hands-on labour",
      "Uses PCR-SSP with SYBR Green melt curve analysis",
      "Rapid identification of HLA and KIR alleles",
      "Eliminates need for post-amplification gels or chips",
    ],
    description:"LinkSēq™ HLA and KIR Typing Kits are rapid, real-time PCR genotyping systems developed by One Lambda / Thermo Fisher Scientific. They are designed for fast, simple identification of Human Leukocyte Antigen (HLA) and Killer-cell Immunoglobulin-like Receptor (KIR) alleles. Utilizing Polymerase Chain Reaction Sequence-Specific Primers (PCR-SSP) paired with SYBR Green melt curve analysis, this platform provides clear results in under 90 minutes with only 10 minutes of hands-on labor Key Product OfferingsLinkSēq HLA Multi-Locus Kits: Comprehensive options like the LinkSēq HLA-ABCDRDQDP+ 384 Kit determine low-resolution to antigen-level configurations across multiple HLA loci simultaneously.LinkSēq Single Antigen Kits: Targeted formulations optimized for rapid, specific allele screening. These include the LinkSēq HLA-B27 Typing Kit and the LinkSēq HLA-B*57:01 Kit.LinkSēq KIR Typing Kits: Specialized kits designed to identify all 15 KIR genes and 2 pseudogenes. Configurations come in both 96-well and 384-well multi-sample tray formats",
    tags:["hla","kir","real-time-pcr","typing"],
    packaging:[
      {name:"LinkSēq HLA Typing Kit",catalogueNumber:"LSEQ-HLA",units:"1 Kit",format:"Real-time PCR kit"},
      {name:"LinkSēq KIR Typing Kit",catalogueNumber:"LSEQ-KIR",units:"1 Kit",format:"Real-time PCR kit"},
    ],
    features:[
      "PCR-SSP (Sequence-Specific Primers) with SYBR Green melt curve analysis",
      "Results in under 90 minutes with only 10 minutes hands-on time",
      "Rapid identification of HLA (Class I and II) and KIR alleles",
      "No post-amplification gels or chips required — safer and more efficient",
      "Compatible with standard real-time PCR thermocyclers",
    ],
    applications:["HLA gene presence/absence typing for clinical and research use","KIR genotyping for NK cell biology and transplant outcome prediction","Haplogroup determination and population studies","High-throughput gene content screening"],
    specs:{"Method":"Real-time PCR","Targets":"HLA genes, KIR genes","Equipment":"Standard real-time PCR thermocycler","Turnaround":"2–4 hours","Regulatory":"CE marked"},
   },

  { id:"ol-linkseq-hpa-abo", name:"LinkSēq™ HPA and ABO Typing Kits", brand:"onelambda", category:"molecular", subcategory:"LinkSeq Real-Time PCR",
    image:"/images/ol-linkseq-hpa-abo.jpeg",
    highlights:[
      "Fast, accurate HLA and ABO tissue/blood grouping results",
      "PCR-SSP with SYBR Green melt-curve analysis",
      "Eliminates post-amplification gels or chips",
      "Identifies HLA Class I (A,B,C) and Class II (DR,DQ,DP) alleles",
    ],
    description:"LinkSēq™ HLA and ABO Typing Kits are rapid molecular genotyping systems manufactured by One Lambda / Thermo Fisher Scientific. They utilize real-time PCR-SSP (Sequence-Specific Priming) and SYBR Green melt-curve analysis to deliver fast, accurate tissue and blood grouping results. These kits eliminate the need for post-amplification gels or chips, vastly improving laboratory safety and efficiency. Core Diagnostic ApplicationsHLA Typing: Identifies Class I (A, B, C) and Class II (DR, DQ, DP) alleles. It serves as a vital pre-transplant screening tool for solid organs and hematopoietic stem cell matching.ABO Blood Genotyping: Resolves discordant serological testing. It successfully distinguishes weak subgroups, separating A1 from non-A1, and B from B3, Bweak, or Bel alleles.Disease Associations: Features dedicated targeted assays for specific genetic conditions, including HLA-B*27 (Ankylosing Spondylitis), Coeliac disease (DQ2/DQ8), and Narcolepsy",
    tags:["hpa","abo","real-time-pcr"],
    packaging:[
      {name:"LinkSēq HPA Typing Kit",catalogueNumber:"LSEQ-HPA",units:"1 Kit",format:"Real-time PCR kit"},
      {name:"LinkSēq ABO Typing Kit",catalogueNumber:"LSEQ-ABO",units:"1 Kit",format:"Real-time PCR kit"},
    ],
    features:[
      "Real-time PCR-SSP (Sequence-Specific Priming) with SYBR Green melt-curve analysis",
      "HLA Typing: Identifies Class I (A,B,C) and Class II (DR,DQ,DP) alleles",
      "ABO Blood Group genotyping for transplant and transfusion medicine",
      "Eliminates post-amplification gels or chips — improved safety and efficiency",
      "Vastly improves laboratory efficiency over traditional gel-based methods",
    ],
    applications:["Human Platelet Antigen (HPA) typing for transfusion medicine","ABO blood group genotyping for transplant and transfusion","Foetal/neonatal alloimmune thrombocytopenia (FNAIT) workup","Platelet matching for refractory patients"],
    specs:{"Method":"Real-time PCR allelic discrimination","Targets":"HPA antigens, ABO blood group alleles","Equipment":"Standard real-time PCR thermocycler","Turnaround":"2–4 hours","Regulatory":"CE marked"},
   },

  { id:"ol-cytokine-genotyping", name:"Cytokine Genotyping Kits", brand:"onelambda", category:"molecular", subcategory:"Non-HLA Genotyping",
    image:"/images/ol-cytokine-genotyping.jpg",
    highlights:[
      "Simple, accurate and economical cytokine SNP detection",
      "PCR-SSP methodology for genomic DNA amplification from whole blood",
      "Targets: TGF-beta, TNF-alpha, IL-10, and other key cytokines",
    ],
    description:"The One Lambda Cytokine Genotyping Tray (manufactured by Thermo Fisher Scientific) is a molecular assay designed to provide a simple, accurate, and economical method for detecting single nucleotide polymorphisms (SNPs) and specific alleles in human cytokine genes. It uses the Polymerase Chain Reaction-Sequence Specific Primers (PCR-SSP) methodology to amplify genomic DNA extracted from whole blood TGF-beta (Transforming Growth Factor – beta) TNF-alpha (Tumor Necrosis Factor – alpha) IL-10 (Interleukin – 10) IL-6 (Interleukin – 6) IFN-gamma (Interferon – gamma)",
    tags:["cytokine","genotyping","non-hla"],
    packaging:[{name:"Cytokine Genotyping Kit",catalogueNumber:"CYTOKGENO",units:"1 Kit",format:"SSP typing"}],
    features:[
      "PCR-SSP (Polymerase Chain Reaction-Sequence Specific Primers) methodology",
      "Detects single nucleotide polymorphisms (SNPs) in human cytokine genes",
      "DNA extracted from whole blood — simple sample preparation",
      "Targets: TGF-beta, TNF-alpha, IL-10, and other clinically relevant cytokines",
      "Simple, accurate, and economical alternative to sequencing-based methods",
    ],
    applications:["Pre-transplant cytokine gene polymorphism profiling","Research into cytokine-mediated graft rejection","Immunogenetics research in inflammatory conditions","Prediction of immune response post-transplant"],
    specs:{"Method":"SSP PCR","Targets":"TNF-α, IL-10, IL-6, IFN-γ and others","Equipment":"Standard thermocycler + gel electrophoresis","Regulatory":"RUO"},
   },

  { id:"ol-kir-sso", name:"KIR SSO Genotyping", brand:"onelambda", category:"molecular", subcategory:"Non-HLA Genotyping",
    image:"/images/ol-kir-sso.jpg",
    highlights:[
      "Identifies presence/absence of KIR genes (16 genes/pseudogenes)",
      "Luminex® xMAP® technology for high-throughput multiplexed analysis",
      "Determines KIR haplotypes (A or B)",
      "Used in transplant medicine and reproductive immunology",
    ],
    description:"KIR SSO (Sequence-Specific Oligonucleotide) genotyping is a molecular technique used to identify the presence or absence of Killer Cell Immunoglobulin-like Receptor (KIR) genes. It utilizes Luminex® xMAP® technology for high-throughput, multiplexed analysis of KIR gene content (16 genes/pseudogenes) to determine KIR haplotypes (A or B). This assay is used in transplant medicine and reproductive immunology to predict outcomes",
    tags:["kir","sso","genotyping"],
    packaging:[{name:"KIR SSO Genotyping Kit",catalogueNumber:"KIRSSO04",units:"1 Kit",format:"Luminex bead kit"}],
    features:[
      "Sequence-Specific Oligonucleotide (SSO) genotyping for KIR gene content",
      "Luminex® xMAP® technology for high-throughput multiplexed analysis",
      "Covers 16 KIR genes and pseudogenes for complete haplotype assignment",
      "Determines KIR haplotypes: A or B",
      "Applications in transplant medicine and reproductive immunology",
    ],
    applications:["KIR gene content typing for HSCT donor selection","NK cell biology and KIR-HLA interaction research","Population genetics and KIR haplotype studies","Post-transplant NK cell reconstitution monitoring"],
    specs:{"Method":"Reverse SSO on Luminex xMAP® beads","KIR Genes":"KIR2DL1-3, KIR2DS1-5, KIR3DL1-3, KIR3DS1 and others","Analyzer":"LABScan3D™","Format":"96-well microplate","Regulatory":"CE marked"},
   },

  { id:"ol-qubit", name:"Qubit™ Fluorometric Quantitation", brand:"onelambda", category:"equipment", subcategory:"Molecular Biology Instrumentation",
    image:"/images/ol-qubit.jpg",
    highlights:[
      "Highly accurate, specific, and sensitive DNA/RNA/protein quantification",
      "Industry standard for NGS and molecular biology applications",
      "Small sample volumes: 1–20 µL",
      "Reliable results in seconds",
    ],
    description:"Qubit™ Fluorometric Quantitation provides highly accurate, specific, and sensitive quantification of DNA, RNA, and protein using target-selective fluorescent dyes. It is the industry standard for Next-Generation Sequencing (NGS) and molecular biology applications, requiring only small sample volumes (1–20 \\(\\mu \\)L) to deliver reliable results in seconds",
    tags:["dna-quantitation","fluorometric","qubit"],
    packaging:[
      {name:"Qubit™ dsDNA HS Assay Kit",catalogueNumber:"Q32851",units:"100 Assays",format:"Fluorometric assay"},
      {name:"Qubit™ dsDNA BR Assay Kit",catalogueNumber:"Q32850",units:"100 Assays",format:"Fluorometric assay"},
    ],
    features:[
      "Target-selective fluorescent dyes for highly specific quantitation",
      "Quantifies DNA, RNA, and protein accurately",
      "Small sample volume requirement: 1–20 µL",
      "Delivers reliable results in seconds",
      "Industry standard for NGS library quantitation",
      "Unaffected by RNA, free nucleotides, or other common contaminants",
    ],
    applications:["DNA quantitation before NGS library preparation","Quality control of DNA extractions","Quantitation of AllType™ NGS and HybriType™ inputs","Verification of library concentrations pre-sequencing"],
    specs:{"Method":"Fluorometric quantitation","Sensitivity":"HS: 10 pg/µL – 100 ng/µL; BR: 2 ng/µL – 1 µg/µL","Sample Volume":"1–20 µL","Instrument":"Qubit™ 4 Fluorometer","Dye":"Proprietary intercalating fluorescent dye"},
   },

  { id:"ol-terasaki-trays", name:"Terasaki HLA Tissue Typing Trays", brand:"onelambda", category:"serological", subcategory:"HLA Tissue Typing Trays",
    image:"/images/ol-terasaki-trays.jpg",
    description:"Complement-dependent cytotoxicity (CDC) Terasaki trays for serological HLA tissue typing — the classic method for pre-transplant crossmatch and HLA antigen identification.", featured:true,
    tags:["serological","cdc","terasaki","hla","tissue-typing"],
    highlights:["Classic CDC method for HLA tissue typing","Class I and Class II formats available","72-well tray format","High antigen coverage"],
    packaging:[
      {name:"Terasaki HLA Class II Tissue Typing Tray, 72 Well",catalogueNumber:"O3DR72",units:"10 Trays",format:"72-well format"},
      {name:"Terasaki HLA Class II Dry Tissue Typing Tray",catalogueNumber:"O3DR72D",units:"10 Trays",format:"72-well format"},
      {name:"Terasaki Special Class I Tissue Typing Set",catalogueNumber:"O3TM144",units:"20 Tests",format:""},
    ],
    relatedProducts:["ol-terasaki-supplement","ol-lmt"],
    features:["Human lymphocyte panels from selected donors","Represents broad range of HLA-A, B, C and DR, DQ specificities","72-well Terasaki microtitre tray format","Ready-to-use cryopreserved cells","Lot-to-lot consistency testing"],
    applications:["HLA antigen typing by CDC","Pre-transplant crossmatch testing","Panel Reactive Antibody (PRA) determination using cell panels","Quality control in serological HLA laboratories"],
    specs:{"Method":"Complement-Dependent Cytotoxicity (CDC)","Format":"72-well Terasaki tray","Cell Types":"T lymphocytes (Class I), B lymphocytes (Class II)","Storage":"Liquid nitrogen","HLA Coverage":"Representative A, B, C, DR, DQ specificities","Regulatory":"CE marked"},
   },

  { id:"ol-dynabeads", name:"Dynabeads™ for Cell Isolation", brand:"onelambda", category:"serological", subcategory:"Serological Reagents",
    image:"/images/ol-dynabeads.jpg",
    highlights:[
      "Rapid isolation of HLA Class II-positive cells from human biological samples",
      "Used for tissue typing and pre-transplant crossmatch assays",
      "Separates specific lymphocyte populations efficiently",
      "By Invitrogen (Thermo Fisher Scientific)",
    ],
    description:"Dynabeads™ HLA Class II (Catalog No. 21004D) by Invitrogen (Thermo Fisher Scientific) is a reagent kit designed for the rapid isolation of HLA Class II-positive cells directly from human biological samples. This product is primarily used in clinical immunology, tissue typing, and pre-transplant crossmatching assays to separate specific lymphocyte populations",
    tags:["dynabeads","cell-isolation","serological"],
    packaging:[
      {name:"Dynabeads™ Pan T (CD2)",catalogueNumber:"DYNAPAT",units:"1 Vial",format:"Magnetic beads"},
      {name:"Dynabeads™ Pan B (CD19)",catalogueNumber:"DYNAPAB",units:"1 Vial",format:"Magnetic beads"},
    ],
    features:[
      "Magnetic bead-based isolation of HLA Class II-positive cells",
      "Works directly from human biological samples — no pre-processing required",
      "Used in clinical immunology, tissue typing, and crossmatching",
      "Separates specific lymphocyte populations for CDC and flow crossmatch",
      "Compatible with standard magnetic separators",
    ],
    applications:["T-lymphocyte isolation for T-cell CDC crossmatch","B-lymphocyte isolation for B-cell CDC crossmatch","Cell separation prior to flow cytometry crossmatch","Purification of lymphocyte populations from peripheral blood"],
    specs:{"Targets":"CD2 (Pan T cells), CD19 (Pan B cells)","Method":"Magnetic bead separation","Purity":">95% target cell population","Equipment":"Standard magnetic separator","Storage":"2–8 °C","Regulatory":"CE marked"},
   },

  { id:"ol-fluoroquench", name:"FluoroQuench™ Staining/Quenching Reagent", brand:"onelambda", category:"serological", subcategory:"Serological Reagents",
    image:"/images/ol-fluoroquench.jpg",
    highlights:[
      "Simultaneously stains lymphocytes and stops complement-dependent cell lysis",
      "Acridine Orange (AO) stains live lymphocytes fluorescent green",
      "Reduces background fluorescence for cleaner CDC readout",
      "Designed for serological HLA microcytotoxicity assays",
    ],
    description:"FluoroQuench™ Staining/Quenching Reagent is a specialized laboratory cocktail manufactured by One Lambda (a Thermo Fisher Scientific brand). It is primarily designed to simultaneously stain lymphocytes, reduce background fluorescence, and stop complement-dependent cell lysis during serological HLA microcytotoxicity assays Core Mechanism and ComponentsAcridine Orange (AO): A fluorescent dye that penetrates viable cell membranes to selectively stain live lymphocytes, making them fluoresce green.Ethidium Bromide (EB): A dye that enters compromised membranes to stain dead cells, making them fluoresce bright red under a microscope.EDTA (Ethylenediaminetetraacetic acid): Acts as a chelating agent to immediately stop complement-dependent cell lysis, freezing the reaction at a specific endpoint.Bovine Hemoglobin: Used alongside proprietary components as a quenching agent to significantly obscure nonspecific background fluorescence.",
    tags:["fluoroquench","cdc","staining"],
    packaging:[{name:"FluoroQuench™",catalogueNumber:"FLUROQUENCH",units:"1 Vial",format:"Reagent"}],
    features:[
      "Dual action: stains lymphocytes AND quenches background fluorescence",
      "Acridine Orange (AO) component selectively stains viable lymphocytes (fluorescent green)",
      "Ethidium Bromide (EB) component stains dead cells (fluorescent red/orange)",
      "Simultaneously stops complement-dependent cell lysis",
      "Optimised for CDC-based HLA microcytotoxicity (Terasaki) assays",
    ],
    applications:["Live/dead cell discrimination in CDC crossmatch assays","Enhanced reading of CDC results by fluorescence microscopy","Standard serological HLA typing CDC protocols"],
    specs:{"Method":"Fluorescence-based live/dead staining","Excitation/Emission":"Compatible with standard fluorescence microscope filters","Volume":"Ready-to-use","Storage":"2–8 °C, protect from light"},
   },

  { id:"ol-labscan3d", name:"LABScan3D™ Multiplex Analyzer", brand:"onelambda", category:"multiplex", subcategory:"Readers & Analysers",
    image:"/images/ol-labscan3d.jpg",
    description:"The LABScan3D™ Multiplex Analyzer is an advanced, high-throughput In Vitro Diagnostic (IVD) certified system distributed by One Lambda (a Thermo Fisher Scientific brand). It is a specialized, brand-labeled configuration of the Luminex FLEXMAP 3D System. The instrument relies on xMAP bead-based suspension technology. It is primarily engineered for precise transplant diagnostics, human leukocyte antigen (HLA) typing, and antibody detection Multiplex Capacity: Processes up to 500 unique bead regions simultaneously in a single sample volume.Fluidics Engineering: Equipped with dual syringe pumps and automated reagent reservoirs to minimize system downtime.Optical Sensors: Utilizes a dual-laser setup featuring a 638 nm classification laser alongside a 532 nm reporter laser.Acquisition Rates: Achieves a standard sample injection throughput rate of 2 µl per second.Software Core: Powered by Luminex xPONENT software for electronic data acquisition, reporting, and data archiving", featured:true,
    tags:["analyzer","hla","transplant","luminex","instrument"],
    highlights:[
      "Advanced high-throughput IVD-certified system for transplant diagnostics",
      "Specialised configuration of the Luminex FLEXMAP 3D System",
      "Processes up to 500 unique bead regions for maximum multiplexing",
      "Engineered for HLA typing, antibody detection, and transplant diagnostics",
    ],
    features:[
      "xMAP bead-based suspension technology with 500-plex capacity",
      "Specialised, brand-labeled configuration of the Luminex FLEXMAP 3D System",
      "Engineered for transplant diagnostics, HLA typing, and antibody detection",
      "IVD (In Vitro Diagnostic) certified system",
      "Compatible with all LABScreen™ and LABType™ One Lambda assay kits",
      "Integrated with HLA Fusion™ software for complete workflow management",
    ],
    applications:["HLA antibody detection using LABScreen™ assays","HLA typing using LABType™ SSO kits","Post-transplant DSA monitoring","Virtual crossmatch support"],
    specs:{"Bead Regions":"500","Lasers":"3 (Red 633nm, Green 532nm, Violet 405nm)","Fluorescent Channels":"10","Sample Throughput":"Up to 96 samples per run","Plate Format":"Standard 96-well microplate","Regulatory Status":"FDA 510(k) cleared, CE marked"},
    packaging:[{name:"LABScan3D™ Analyzer",catalogueNumber:"LABScan3D",units:"1 Instrument",format:"Benchtop analyser"}],
    relatedProducts:["ol-labscreen-sa1","ol-labscreen-sa2","ol-labtype-sso","ol-fusion"] },

  { id:"ol-labscan100", name:"LABScan™ 100 Analyser", brand:"onelambda", category:"multiplex", subcategory:"Readers & Analysers",
    image:"/images/ol-labscan100.png",
    highlights:[
      "Flow-based multiplex reader powered by Luminex xMAP® Technology",
      "Simultaneously identifies up to 100 unique analytes per microplate reaction",
      "Used for HLA typing and antibody detection in transplant labs",
      "Distributed by Thermo Fisher Scientific (One Lambda)",
    ],
    description:"The LABScan™ 100 Analyser is a flow-based multiplex laboratory reader manufactured by Luminex Corporation and heavily utilized in transplantation immunology. Powered by proprietary xMAP® Technology, the system can simultaneously identify, detect, and measure up to 100 unique analytes inside a single microplate reaction volume. It is broadly distributed by transplant diagnostic companies like Thermo Fisher Scientific (One Lambda) and VH Bio for human leukocyte antigen (HLA) typing and antibody detection",
    tags:["analyzer","luminex","instrument"],
    packaging:[{name:"LABScan™ 100",catalogueNumber:"LABScan100",units:"1 Instrument",format:"Benchtop analyser"}],
    relatedProducts:["ol-labscan3d"],
    features:[
      "Luminex xMAP® Technology: simultaneous detection of up to 100 analytes",
      "Single microplate reaction volume for efficient processing",
      "Used for HLA typing and antibody detection in transplantation immunology",
      "Compatible with all One Lambda Luminex-based assay kits",
      "Flow-based reader with automated data acquisition",
    ],
    applications:["HLA antibody detection with LABScreen™ assays","HLA typing with LABType™ SSO kits","Entry-level multiplex bead reading in transplant labs"],
    specs:{"Platform":"Luminex 100/200 compatible","Bead Regions":"Up to 100","Lasers":"2 (Red 633nm, Green 532nm)","Throughput":"Up to 96 samples/run","Software":"LABScan™ Manager","Regulatory":"FDA 510(k) cleared, CE marked"},
   },

  { id:"ol-fusion", name:"HLA Fusion™ Software", brand:"onelambda", category:"transplant", subcategory:"Software",
    image:"/images/ol-fusion.jpg",
    description:"HLA Fusion™ Software from Thermo Fisher Scientific (One Lambda) is a comprehensive, widely used, and validated diagnostic software platform for analyzing molecular typing and antibody screening data in transplant diagnostics. It integrates with LABScreen, LABType, FlowPRA, and other assays, offering advanced tools for epitope analysis, patient record management, and reporting",
    tags:["software","hla","transplant","lims"],
    highlights:[
      "Comprehensive, validated diagnostic software for transplant diagnostics",
      "Integrates with LABScreen™, LABType™, FlowPRA™ and other assays",
      "Advanced tools for epitope analysis and patient record management",
      "Widely used and validated in transplant immunology laboratories worldwide",
    ],
    specs:{"Platform":"Windows desktop application","LIS Interface":"HL7 bidirectional","Compliance":"21 CFR Part 11"},
    packaging:[{name:"HLA Fusion™ Software",catalogueNumber:"HLAFusion4",units:"1 License",format:"Software license"}],
    relatedProducts:["ol-labscan3d","ol-labscreen-sa1"] },

  { id:"ol-typestream", name:"TypeStream™ Visual NGS Analysis Software", brand:"onelambda", category:"ngs", subcategory:"Software",
    image:"/images/ol-typestream.jpeg",
    highlights:[
      "Standalone bioinformatics platform for NGS HLA genotyping analysis",
      "Automates processing of AllType™ and HybriType™ NGS data",
      "Processes Illumina FASTQ and Ion Torrent data formats",
      "Enables rapid automated analysis and gene copy number detection",
    ],
    description:"TypeStream™ Visual NGS Analysis Software (TSV) is a standalone bioinformatics platform developed by One Lambda (a Thermo Fisher Scientific brand). It automates the genotyping and analysis of Next-Generation Sequencing (NGS) data for Human Leukocyte Antigen (HLA) typing. The software is specifically tailored to process data generated by AllType and HybriType NGS assays",
    tags:["software","ngs","analysis","hla"],
    packaging:[{name:"TypeStream™ Visual Software",catalogueNumber:"TYPESTREAM",units:"1 License",format:"Software license"}],
    relatedProducts:["ol-alltype-ngs","ol-alltype-fastplex"],
    features:[
      "Automates HLA genotyping from NGS sequencing data",
      "Compatible with AllType™ and HybriType™ NGS assay outputs",
      "Processes Illumina (FASTQ) and Ion Torrent sequencing data",
      "Rapid automated analysis with gene copy number detection",
      "Integration with One Lambda HLA Fusion™ for reporting and analytics",
      "Phased allele assignment with quality metrics and QC reporting",
    ],
    applications:["NGS analysis for AllType™ and AllType™ FASTplex™ assays","NGS analysis for HybriType™ hybrid capture data","Automated high-throughput typing result generation","Bioinformatics pipeline for HLA NGS data"],
    specs:{"Platform":"Windows standalone software","Compatible Sequencers":"Illumina (FASTQ), Ion Torrent (BAM)","Compatible Assays":"AllType™ NGS, FASTplex™, HybriType™","Output":"Phased allele-level genotypes","Export":"HLA Fusion™, CSV, PDF","Regulatory":"CE-IVD"},
   },

  { id:"ol-hla-pro", name:"One Lambda™ HLA PRO Automated Pipettor", brand:"onelambda", category:"equipment", subcategory:"Automated Pipettor",
    image:"/images/ol-hla-pro.jpeg",
    highlights:[
      "Built on the high-performance Tecan Fluent® platform",
      "Automates complex sample preparation for transplant diagnostics",
      "Increases efficiency, precision, and consistency in high-throughput labs",
      "Modular design for general laboratory use (GLU)",
    ],
    description:"The One Lambda™ HLA PRO Automated Pipettor is a modular, general laboratory use (GLU) automated liquid handling system designed to streamline transplant diagnostic workflows. Built on the high-performance Tecan Fluent® platform, it automates complex sample preparation to increase efficiency, precision, and consistency in high-throughput histocompatibility and immunogenetics laboratories",
    tags:["automation","pipettor","instrument"],
    packaging:[{name:"One Lambda™ HLA PRO",catalogueNumber:"HLA-PRO",units:"1 Instrument",format:"Automated pipettor"}],
    relatedProducts:["ol-labscan3d","ol-labtype-sso"],
    features:[
      "Modular automated liquid handling system built on the Tecan Fluent® platform",
      "Automates complex sample preparation for transplant diagnostic workflows",
      "Increases efficiency, precision, and consistency in histocompatibility labs",
      "Designed for high-throughput histocompatibility and immunogenetics laboratories",
      "Compatible with One Lambda HLA typing and antibody detection workflows",
      "General laboratory use (GLU) certified",
    ],
    applications:["Automated sample loading for HLA typing assays","High-throughput HLA laboratory automation","Error reduction in antibody detection pipetting","Standardisation of repetitive liquid handling steps"],
    specs:{"Type":"Automated modular pipettor","Compatible Assays":"Micro SSP™, LABType™ SSO, LABScreen™ SAB","Plate Format":"96-well microplate and SSP trays","Sample Tracking":"Barcode integrated","Software":"Instrument-specific control software"},
   },

  // ═══ ONE LAMBDA — POST-TRANSPLANT MONITORING ═══════════════════════════════

  { id:"ol-accept-cfdna", name:"One Lambda Devyser Accept cfDNA Assay", brand:"onelambda", category:"posttransplant", subcategory:"Donor-Derived Cell-Free DNA",
    image:"/images/ol-accept-cfdna.jpg",
    description:"The One Lambda Devyser Accept cfDNA Assay is a highly sensitive, single-tube Next-Generation Sequencing (NGS) assay designed for the detection and relative quantification of donor-derived cell-free DNA (dd-cfDNA) in post-transplant human plasma samples. Developed through a partnership between Devyser and Thermo Fisher Scientific, the assay allows in-house HLA and transplant laboratories to track solid organ graft health and catch potential allograft rejections earlier than traditional methods like serum creatinine monitoring", featured:true,
    tags:["cfdna","post-transplant","ngs","monitoring","allograft"],
    highlights:[
      "Highly sensitive single-tube NGS assay for dd-cfDNA detection",
      "Developed by Devyser in partnership with Thermo Fisher Scientific",
      "Enables in-house HLA labs to track solid organ graft health",
      "Catches potential allograft rejections earlier than traditional methods",
    ],
    specs:{"LOD":"0.1% dd-cfDNA","Method":"50-indel multiplex PCR + NGS","Platforms":"Illumina","Hands-on Time":"< 45 minutes","Workflow":"~1 day","Regulatory":"CE-IVD marked"},
    packaging:[{name:"Devyser Accept cfDNA Assay Kit",catalogueNumber:"ACCEPT-CFDNA",units:"24 Samples",format:"NGS library prep kit"}],
    relatedProducts:["ol-chimerism-ngs","ol-alltype-ngs"],
    features:[
      "Highly sensitive NGS assay for donor-derived cell-free DNA (dd-cfDNA) detection",
      "Single-tube format for simplified workflow",
      "Developed through Devyser and Thermo Fisher Scientific partnership",
      "Enables in-house transplant labs to monitor solid organ graft health",
      "Earlier rejection detection than traditional biopsy or DSA testing",
      "Quantification of dd-cfDNA in post-transplant plasma samples",
    ],
    applications:["Non-invasive allograft injury monitoring in solid organ transplant recipients","Early detection of rejection before clinical symptoms","Complement to biopsy and DSA monitoring","Post-transplant surveillance in kidney, heart, lung, and liver transplants"],
   },

  { id:"ol-chimerism-ngs", name:"One Lambda Devyser Chimerism NGS Assay", brand:"onelambda", category:"posttransplant", subcategory:"Chimerism Monitoring",
    image:"/images/ol-chimerism-ngs.jpg",
    highlights:[
      "Targeted NGS solution for post-transplant chimerism monitoring",
      "Tracks donor and recipient DNA proportions following HSCT",
      "Detects early graft rejection or disease relapse",
      "Distributed via Thermo Fisher Scientific (One Lambda)",
    ],
    description:"The One Lambda Devyser Chimerism NGS Assay is a targeted next-generation sequencing solution designed for high-throughput post-transplant monitoring. Distributed via Thermo Fisher Scientific, it tracks donor and recipient DNA proportions following hematopoietic stem cell transplantation (HSCT) to detect early graft rejection or disease relapse",
    tags:["chimerism","post-transplant","ngs","monitoring"],
    packaging:[{name:"Devyser Chimerism NGS Kit",catalogueNumber:"CHIM-NGS",units:"24 Samples",format:"NGS kit"}],
    relatedProducts:["ol-chimerism","ol-accept-cfdna"],
    features:[
      "Targeted next-generation sequencing for high-throughput chimerism monitoring",
      "Tracks donor and recipient DNA proportions after haematopoietic stem cell transplantation",
      "Early detection of graft rejection or disease relapse",
      "Automated analysis with Advyser Chimerism software",
      "High sensitivity for minor chimerism detection",
    ],
    applications:["Post-HSCT engraftment monitoring","Detection of impending graft failure or relapse","Lineage-specific chimerism analysis","Minimal residual disease (MRD) surrogate marker"],
    specs:{"Method":"NGS-based indel marker chimerism","Sensitivity":"Down to 0.1% minor chimerism","Platform":"Illumina","Software":"Advyser Chimerism","Sample Types":"Whole blood, bone marrow","Regulatory":"CE marked"},
   },

  { id:"ol-chimerism", name:"One Lambda Devyser Chimerism Assay", brand:"onelambda", category:"posttransplant", subcategory:"Chimerism Monitoring",
    image:"/images/ol-chimerism.jpeg",
    highlights:[
      "Targeted NGS solution for post-transplant chimerism monitoring",
      "Tracks donor and recipient DNA proportions following HSCT",
      "Detects early graft rejection or disease relapse",
      "Distributed via Thermo Fisher Scientific (One Lambda)",
    ],
    description:"The One Lambda Devyser Chimerism NGS Assay is a targeted next-generation sequencing solution designed for high-throughput post-transplant monitoring. Distributed via Thermo Fisher Scientific, it tracks donor and recipient DNA proportions following hematopoietic stem cell transplantation (HSCT) to detect early graft rejection or disease relapse",
    tags:["chimerism","post-transplant","str","monitoring"],
    packaging:[{name:"Devyser Chimerism STR Kit",catalogueNumber:"CHIM-STR",units:"24 Samples",format:"PCR kit"}],
    relatedProducts:["ol-chimerism-ngs"],
    features:[
      "Targeted next-generation sequencing for post-transplant monitoring",
      "Tracks donor and recipient DNA following haematopoietic stem cell transplantation",
      "Early detection of graft failure or disease relapse",
      "Automated Advyser Chimerism software analysis",
    ],
    applications:["Post-HSCT engraftment monitoring by STR","Donor and recipient chimerism percentage calculation","Relapse detection following allogeneic stem cell transplantation","Lineage-specific chimerism in clinical practice"],
    specs:{"Method":"Short Tandem Repeat (STR) PCR","Detection":"Capillary electrophoresis fluorescence","Sensitivity":"~1–5% minor chimerism","Software":"GeneMapper or equivalent","Regulatory":"CE marked"},
   },

  // ═══ OTHER BRANDS ══════════════════════════════════════════════════════════

  { id:"luminex-magpix", name:"MAGPIX® System", brand:"luminex", category:"multiplex", description:"Compact magnetic-bead multiplex platform delivering up to 50-plex per well.", featured:true, tags:["xmap","compact"], packaging:[{name:"MAGPIX® System",catalogueNumber:"MAGPIX",units:"1 Instrument",format:"Benchtop analyser"}] },
  { id:"luminex-flexmap3d", name:"FLEXMAP 3D® System", brand:"luminex", category:"multiplex", description:"High-throughput xMAP analyzer with 500-plex capability for biomarker discovery.", tags:["xmap","research"] },
  { id:"luminex-intelliflex", name:"xMAP INTELLIFLEX™", brand:"luminex", category:"multiplex", description:"Next-generation flow-based multiplexer with dual reporter channels.", tags:["xmap"] },
  { id:"merck-cd3", name:"Anti-CD3 Monoclonal Antibody", brand:"merck", category:"antibodies", description:"Mouse monoclonal targeting human CD3 — validated for FC, IHC, and WB." },
  { id:"merck-sybr", name:"SYBR® Green qPCR Master Mix", brand:"merck", category:"molecular", description:"Optimized 2× master mix for high-sensitivity real-time PCR.", featured:true },
  { id:"diasorin-liaison-xl", name:"LIAISON® XL Immunoassay Analyzer", brand:"diasorin", category:"immuno", description:"Fully automated chemiluminescent platform with up to 180 tests/hour.", featured:true },
  { id:"diasorin-vitd", name:"LIAISON® Vitamin D Total Assay", brand:"diasorin", category:"immuno", description:"Fully automated 25-OH vitamin D quantification — clinical reference standard." },
  { id:"cytek-aurora", name:"Cytek® Aurora Flow Cytometer", brand:"cytek", category:"flow", description:"Up to 5-laser, 64-color full-spectrum flow cytometer for complex panels.", featured:true },
  { id:"cytek-northernlights", name:"Cytek® Northern Lights™", brand:"cytek", category:"flow", description:"Compact spectral flow cytometer purpose-built for clinical research." },
  { id:"ngene-onco", name:"ONCOaccuPanel™ Pan-Cancer NGS", brand:"ngene", category:"ngs", description:"323-gene targeted panel covering all major solid-tumor biomarkers.", featured:true },
  { id:"hkm-centrifuge", name:"HKM High-Speed Refrigerated Centrifuge", brand:"hkm", category:"equipment", description:"Up to 21,000 × g with ±1 °C temperature control." },
  { id:"hkm-co2", name:"HKM CO₂ Incubator", brand:"hkm", category:"equipment", description:"Direct-heat 170 L incubator with HEPA-filtered chamber." },
  { id:"hkm-bsc", name:"HKM Class II Biosafety Cabinet", brand:"hkm", category:"equipment", description:"Type A2 cabinet with EN-12469 certification for BSL-2 handling." },
  { id:"bl-cd4-pe", name:"PE Anti-Human CD4 (Clone OKT4)", brand:"biolegend", category:"antibodies", description:"PE-conjugated antibody validated for flow cytometry.", featured:true },
  { id:"bl-elisa-max", name:"ELISA MAX™ Standard Set", brand:"biolegend", category:"immuno", description:"Pre-titered antibody pairs for ELISA development across hundreds of analytes." },
];

export function brandById(id: string) { return brands.find(b => b.id === id)!; }
export function categoryById(id: string) { return categories.find(c => c.id === id)!; }
export function productById(id: string) { return products.find(p => p.id === id); }
export function productsByBrand(id: string) { return products.filter(p => p.brand === id); }
export function productsByCategory(id: string) { return products.filter(p => p.category === id); }
export function featuredProducts() { return products.filter(p => p.featured); }
